package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	"github.com/Gyt-project/backend-api/pkg/gql/model"
	pb "github.com/Gyt-project/backend-api/pkg/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	resp, err := r.Client.Register(grpcCtx(ctx), &pb.RegisterRequest{
		Username:    input.Username,
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: input.DisplayName,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	resp, err := r.Client.Login(grpcCtx(ctx), &pb.LoginRequest{
		Login:    input.Login,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	resp, err := r.Client.RefreshToken(grpcCtx(ctx), &pb.RefreshTokenRequest{
		RefreshToken: refreshToken,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	resp, err := r.Client.UpdateUser(grpcCtx(ctx), &pb.UpdateUserRequest{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
		AvatarUrl:   input.AvatarURL,
		Email:       input.Email,
		Password:    input.Password,
	})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, username string) (bool, error) {
	_, err := r.Client.DeleteUser(grpcCtx(ctx), &pb.DeleteUserRequest{Username: username})
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddSSHKey is the resolver for the addSSHKey field.
func (r *mutationResolver) AddSSHKey(ctx context.Context, input model.AddSSHKeyInput) (*model.SSHKey, error) {
	resp, err := r.Client.AddSSHKey(grpcCtx(ctx), &pb.AddSSHKeyRequest{
		Name:      input.Name,
		PublicKey: input.PublicKey,
	})
	if err != nil {
		return nil, err
	}
	return pbSSHKeyToModel(resp), nil
}

// DeleteSSHKey is the resolver for the deleteSSHKey field.
func (r *mutationResolver) DeleteSSHKey(ctx context.Context, keyID string) (bool, error) {
	id, err := strconv.ParseUint(keyID, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.DeleteSSHKey(grpcCtx(ctx), &pb.DeleteSSHKeyRequest{KeyId: id})
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateRepository is the resolver for the createRepository field.
func (r *mutationResolver) CreateRepository(ctx context.Context, input model.CreateRepoInput) (*model.Repository, error) {
	resp, err := r.Client.CreateRepository(grpcCtx(ctx), &pb.CreateRepoRequest{
		Name:        input.Name,
		Description: input.Description,
		IsPrivate:   input.IsPrivate,
		OrgName:     input.OrgName,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

// UpdateRepository is the resolver for the updateRepository field.
func (r *mutationResolver) UpdateRepository(ctx context.Context, input model.UpdateRepoInput) (*model.Repository, error) {
	resp, err := r.Client.UpdateRepository(grpcCtx(ctx), &pb.UpdateRepoRequest{
		Owner:         input.Owner,
		Name:          input.Name,
		Description:   input.Description,
		IsPrivate:     input.IsPrivate,
		DefaultBranch: input.DefaultBranch,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

// DeleteRepository is the resolver for the deleteRepository field.
func (r *mutationResolver) DeleteRepository(ctx context.Context, owner string, name string) (bool, error) {
	_, err := r.Client.DeleteRepository(grpcCtx(ctx), &pb.DeleteRepoRequest{Owner: owner, Name: name})
	if err != nil {
		return false, err
	}
	return true, nil
}

// RenameRepository is the resolver for the renameRepository field.
func (r *mutationResolver) RenameRepository(ctx context.Context, input model.RenameRepoInput) (*model.Repository, error) {
	resp, err := r.Client.RenameRepository(grpcCtx(ctx), &pb.RenameRepoRequest{
		Owner:   input.Owner,
		OldName: input.OldName,
		NewName: input.NewName,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

// SetDefaultBranch is the resolver for the setDefaultBranch field.
func (r *mutationResolver) SetDefaultBranch(ctx context.Context, owner string, name string, branchName string) (*model.DefaultBranchResponse, error) {
	resp, err := r.Client.SetDefaultBranch(grpcCtx(ctx), &pb.SetDefaultBranchRequest{
		Owner:      owner,
		Name:       name,
		BranchName: branchName,
	})
	if err != nil {
		return nil, err
	}
	return &model.DefaultBranchResponse{BranchName: resp.GetBranchName()}, nil
}

// CreateTag is the resolver for the createTag field.
func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.TagDetail, error) {
	resp, err := r.Client.CreateTag(grpcCtx(ctx), &pb.CreateTagRequest{
		Owner:   input.Owner,
		Name:    input.Name,
		TagName: input.TagName,
		Target:  input.Target,
		Message: input.Message,
	})
	if err != nil {
		return nil, err
	}
	return &model.TagDetail{
		Tag:    pbTagToModel(resp.GetTag()),
		Commit: pbCommitToModel(resp.GetCommit()),
	}, nil
}

// DeleteTag is the resolver for the deleteTag field.
func (r *mutationResolver) DeleteTag(ctx context.Context, owner string, name string, tagName string) (bool, error) {
	_, err := r.Client.DeleteTag(grpcCtx(ctx), &pb.DeleteTagRequest{Owner: owner, Name: name, TagName: tagName})
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddCollaborator is the resolver for the addCollaborator field.
func (r *mutationResolver) AddCollaborator(ctx context.Context, input model.AddCollaboratorInput) (bool, error) {
	_, err := r.Client.AddCollaborator(grpcCtx(ctx), &pb.AddCollaboratorRequest{
		Owner:       input.Owner,
		Name:        input.Name,
		Username:    input.Username,
		AccessLevel: input.AccessLevel,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// RemoveCollaborator is the resolver for the removeCollaborator field.
func (r *mutationResolver) RemoveCollaborator(ctx context.Context, owner string, name string, username string) (bool, error) {
	_, err := r.Client.RemoveCollaborator(grpcCtx(ctx), &pb.RemoveCollaboratorRequest{
		Owner:    owner,
		Name:     name,
		Username: username,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// UpdateCollaborator is the resolver for the updateCollaborator field.
func (r *mutationResolver) UpdateCollaborator(ctx context.Context, input model.UpdateCollaboratorInput) (bool, error) {
	_, err := r.Client.UpdateCollaborator(grpcCtx(ctx), &pb.UpdateCollaboratorRequest{
		Owner:       input.Owner,
		Name:        input.Name,
		Username:    input.Username,
		AccessLevel: input.AccessLevel,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// CreateOrganization is the resolver for the createOrganization field.
func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrgInput) (*model.Organization, error) {
	resp, err := r.Client.CreateOrganization(grpcCtx(ctx), &pb.CreateOrgRequest{
		Name:        input.Name,
		DisplayName: input.DisplayName,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

// UpdateOrganization is the resolver for the updateOrganization field.
func (r *mutationResolver) UpdateOrganization(ctx context.Context, input model.UpdateOrgInput) (*model.Organization, error) {
	resp, err := r.Client.UpdateOrganization(grpcCtx(ctx), &pb.UpdateOrgRequest{
		Name:        input.Name,
		DisplayName: input.DisplayName,
		Description: input.Description,
		AvatarUrl:   input.AvatarURL,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

// DeleteOrganization is the resolver for the deleteOrganization field.
func (r *mutationResolver) DeleteOrganization(ctx context.Context, name string) (bool, error) {
	_, err := r.Client.DeleteOrganization(grpcCtx(ctx), &pb.DeleteOrgRequest{Name: name})
	if err != nil {
		return false, err
	}
	return true, nil
}

// AddOrgMember is the resolver for the addOrgMember field.
func (r *mutationResolver) AddOrgMember(ctx context.Context, input model.AddOrgMemberInput) (*model.OrgMember, error) {
	resp, err := r.Client.AddOrgMember(grpcCtx(ctx), &pb.AddOrgMemberRequest{
		OrgName:  input.OrgName,
		Username: input.Username,
		Role:     input.Role,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

// UpdateOrgMember is the resolver for the updateOrgMember field.
func (r *mutationResolver) UpdateOrgMember(ctx context.Context, input model.UpdateOrgMemberInput) (*model.OrgMember, error) {
	resp, err := r.Client.UpdateOrgMember(grpcCtx(ctx), &pb.UpdateOrgMemberRequest{
		OrgName:  input.OrgName,
		Username: input.Username,
		Role:     input.Role,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

// RemoveOrgMember is the resolver for the removeOrgMember field.
func (r *mutationResolver) RemoveOrgMember(ctx context.Context, orgName string, username string) (bool, error) {
	_, err := r.Client.RemoveOrgMember(grpcCtx(ctx), &pb.RemoveOrgMemberRequest{
		OrgName:  orgName,
		Username: username,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// StarRepository is the resolver for the starRepository field.
func (r *mutationResolver) StarRepository(ctx context.Context, owner string, name string) (bool, error) {
	_, err := r.Client.StarRepository(grpcCtx(ctx), &pb.StarRepoRequest{Owner: owner, Name: name})
	return err == nil, err
}

// UnstarRepository is the resolver for the unstarRepository field.
func (r *mutationResolver) UnstarRepository(ctx context.Context, owner string, name string) (bool, error) {
	_, err := r.Client.UnstarRepository(grpcCtx(ctx), &pb.UnstarRepoRequest{Owner: owner, Name: name})
	return err == nil, err
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, input model.CreateLabelInput) (*model.Label, error) {
	resp, err := r.Client.CreateLabel(grpcCtx(ctx), &pb.CreateLabelRequest{
		Owner:       input.Owner,
		Repo:        input.Repo,
		Name:        input.Name,
		Color:       input.Color,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return pbLabelToModel(resp), nil
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, input model.UpdateLabelInput) (*model.Label, error) {
	resp, err := r.Client.UpdateLabel(grpcCtx(ctx), &pb.UpdateLabelRequest{
		Owner:       input.Owner,
		Repo:        input.Repo,
		Name:        input.Name,
		NewName:     input.NewName,
		Color:       input.Color,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return pbLabelToModel(resp), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, owner string, repo string, name string) (bool, error) {
	_, err := r.Client.DeleteLabel(grpcCtx(ctx), &pb.DeleteLabelRequest{Owner: owner, Repo: repo, Name: name})
	return err == nil, err
}

// CreateIssue is the resolver for the createIssue field.
func (r *mutationResolver) CreateIssue(ctx context.Context, input model.CreateIssueInput) (*model.Issue, error) {
	resp, err := r.Client.CreateIssue(grpcCtx(ctx), &pb.CreateIssueRequest{
		Owner:     input.Owner,
		Repo:      input.Repo,
		Title:     input.Title,
		Body:      input.Body,
		Assignees: input.Assignees,
		Labels:    input.Labels,
	})
	if err != nil {
		return nil, err
	}
	return pbIssueToModel(resp), nil
}

// UpdateIssue is the resolver for the updateIssue field.
func (r *mutationResolver) UpdateIssue(ctx context.Context, input model.UpdateIssueInput) (*model.Issue, error) {
	resp, err := r.Client.UpdateIssue(grpcCtx(ctx), &pb.UpdateIssueRequest{
		Owner:  input.Owner,
		Repo:   input.Repo,
		Number: int32(input.Number),
		Title:  input.Title,
		Body:   input.Body,
	})
	if err != nil {
		return nil, err
	}
	return pbIssueToModel(resp), nil
}

// CloseIssue is the resolver for the closeIssue field.
func (r *mutationResolver) CloseIssue(ctx context.Context, owner string, repo string, number int) (*model.Issue, error) {
	resp, err := r.Client.CloseIssue(grpcCtx(ctx), &pb.CloseIssueRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbIssueToModel(resp), nil
}

// ReopenIssue is the resolver for the reopenIssue field.
func (r *mutationResolver) ReopenIssue(ctx context.Context, owner string, repo string, number int) (*model.Issue, error) {
	resp, err := r.Client.ReopenIssue(grpcCtx(ctx), &pb.ReopenIssueRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbIssueToModel(resp), nil
}

// AddIssueLabel is the resolver for the addIssueLabel field.
func (r *mutationResolver) AddIssueLabel(ctx context.Context, owner string, repo string, number int, labelName string) (bool, error) {
	_, err := r.Client.AddIssueLabel(grpcCtx(ctx), &pb.AddIssueLabelRequest{Owner: owner, Repo: repo, Number: int32(number), LabelName: labelName})
	return err == nil, err
}

// RemoveIssueLabel is the resolver for the removeIssueLabel field.
func (r *mutationResolver) RemoveIssueLabel(ctx context.Context, owner string, repo string, number int, labelName string) (bool, error) {
	_, err := r.Client.RemoveIssueLabel(grpcCtx(ctx), &pb.RemoveIssueLabelRequest{Owner: owner, Repo: repo, Number: int32(number), LabelName: labelName})
	return err == nil, err
}

// AddIssueAssignee is the resolver for the addIssueAssignee field.
func (r *mutationResolver) AddIssueAssignee(ctx context.Context, owner string, repo string, number int, username string) (bool, error) {
	_, err := r.Client.AddIssueAssignee(grpcCtx(ctx), &pb.AddIssueAssigneeRequest{Owner: owner, Repo: repo, Number: int32(number), Username: username})
	return err == nil, err
}

// RemoveIssueAssignee is the resolver for the removeIssueAssignee field.
func (r *mutationResolver) RemoveIssueAssignee(ctx context.Context, owner string, repo string, number int, username string) (bool, error) {
	_, err := r.Client.RemoveIssueAssignee(grpcCtx(ctx), &pb.RemoveIssueAssigneeRequest{Owner: owner, Repo: repo, Number: int32(number), Username: username})
	return err == nil, err
}

// CreateIssueComment is the resolver for the createIssueComment field.
func (r *mutationResolver) CreateIssueComment(ctx context.Context, owner string, repo string, number int, body string) (*model.IssueComment, error) {
	resp, err := r.Client.CreateIssueComment(grpcCtx(ctx), &pb.CreateIssueCommentRequest{Owner: owner, Repo: repo, Number: int32(number), Body: body})
	if err != nil {
		return nil, err
	}
	return pbIssueCommentToModel(resp), nil
}

// UpdateIssueComment is the resolver for the updateIssueComment field.
func (r *mutationResolver) UpdateIssueComment(ctx context.Context, owner string, repo string, commentID string, body string) (*model.IssueComment, error) {
	id, err := strconv.ParseUint(commentID, 10, 64)
	if err != nil {
		return nil, err
	}
	resp, err := r.Client.UpdateIssueComment(grpcCtx(ctx), &pb.UpdateIssueCommentRequest{Owner: owner, Repo: repo, CommentId: id, Body: body})
	if err != nil {
		return nil, err
	}
	return pbIssueCommentToModel(resp), nil
}

// DeleteIssueComment is the resolver for the deleteIssueComment field.
func (r *mutationResolver) DeleteIssueComment(ctx context.Context, owner string, repo string, commentID string) (bool, error) {
	id, err := strconv.ParseUint(commentID, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.DeleteIssueComment(grpcCtx(ctx), &pb.DeleteIssueCommentRequest{Owner: owner, Repo: repo, CommentId: id})
	return err == nil, err
}

// CreatePullRequest is the resolver for the createPullRequest field.
func (r *mutationResolver) CreatePullRequest(ctx context.Context, input model.CreatePRInput) (*model.PullRequest, error) {
	resp, err := r.Client.CreatePullRequest(grpcCtx(ctx), &pb.CreatePRRequest{
		Owner:      input.Owner,
		Repo:       input.Repo,
		Title:      input.Title,
		HeadBranch: input.HeadBranch,
		BaseBranch: input.BaseBranch,
		Body:       input.Body,
		Assignees:  input.Assignees,
		Labels:     input.Labels,
	})
	if err != nil {
		return nil, err
	}
	return pbPRToModel(resp), nil
}

// UpdatePullRequest is the resolver for the updatePullRequest field.
func (r *mutationResolver) UpdatePullRequest(ctx context.Context, input model.UpdatePRInput) (*model.PullRequest, error) {
	resp, err := r.Client.UpdatePullRequest(grpcCtx(ctx), &pb.UpdatePRRequest{
		Owner:  input.Owner,
		Repo:   input.Repo,
		Number: int32(input.Number),
		Title:  input.Title,
		Body:   input.Body,
		Base:   input.Base,
	})
	if err != nil {
		return nil, err
	}
	return pbPRToModel(resp), nil
}

// MergePullRequest is the resolver for the mergePullRequest field.
func (r *mutationResolver) MergePullRequest(ctx context.Context, input model.MergePRInput) (*model.MergePRResponse, error) {
	resp, err := r.Client.MergePullRequest(grpcCtx(ctx), &pb.MergePRRequest{
		Owner:         input.Owner,
		Repo:          input.Repo,
		Number:        int32(input.Number),
		MergeMethod:   input.MergeMethod,
		CommitTitle:   input.CommitTitle,
		CommitMessage: input.CommitMessage,
	})
	if err != nil {
		return nil, err
	}
	return &model.MergePRResponse{Merged: resp.GetMerged(), Sha: resp.GetSha(), Message: resp.GetMessage()}, nil
}

// ClosePullRequest is the resolver for the closePullRequest field.
func (r *mutationResolver) ClosePullRequest(ctx context.Context, owner string, repo string, number int) (*model.PullRequest, error) {
	resp, err := r.Client.ClosePullRequest(grpcCtx(ctx), &pb.ClosePRRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbPRToModel(resp), nil
}

// ReopenPullRequest is the resolver for the reopenPullRequest field.
func (r *mutationResolver) ReopenPullRequest(ctx context.Context, owner string, repo string, number int) (*model.PullRequest, error) {
	resp, err := r.Client.ReopenPullRequest(grpcCtx(ctx), &pb.ReopenPRRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbPRToModel(resp), nil
}

// AddPRLabel is the resolver for the addPRLabel field.
func (r *mutationResolver) AddPRLabel(ctx context.Context, owner string, repo string, number int, labelName string) (bool, error) {
	_, err := r.Client.AddPRLabel(grpcCtx(ctx), &pb.AddPRLabelRequest{Owner: owner, Repo: repo, Number: int32(number), LabelName: labelName})
	return err == nil, err
}

// RemovePRLabel is the resolver for the removePRLabel field.
func (r *mutationResolver) RemovePRLabel(ctx context.Context, owner string, repo string, number int, labelName string) (bool, error) {
	_, err := r.Client.RemovePRLabel(grpcCtx(ctx), &pb.RemovePRLabelRequest{Owner: owner, Repo: repo, Number: int32(number), LabelName: labelName})
	return err == nil, err
}

// AddPRAssignee is the resolver for the addPRAssignee field.
func (r *mutationResolver) AddPRAssignee(ctx context.Context, owner string, repo string, number int, username string) (bool, error) {
	_, err := r.Client.AddPRAssignee(grpcCtx(ctx), &pb.AddPRAssigneeRequest{Owner: owner, Repo: repo, Number: int32(number), Username: username})
	return err == nil, err
}

// RemovePRAssignee is the resolver for the removePRAssignee field.
func (r *mutationResolver) RemovePRAssignee(ctx context.Context, owner string, repo string, number int, username string) (bool, error) {
	_, err := r.Client.RemovePRAssignee(grpcCtx(ctx), &pb.RemovePRAssigneeRequest{Owner: owner, Repo: repo, Number: int32(number), Username: username})
	return err == nil, err
}

// CreatePRComment is the resolver for the createPRComment field.
func (r *mutationResolver) CreatePRComment(ctx context.Context, input model.CreatePRCommentInput) (*model.PRComment, error) {
	resp, err := r.Client.CreatePRComment(grpcCtx(ctx), &pb.CreatePRCommentRequest{
		Owner:  input.Owner,
		Repo:   input.Repo,
		Number: int32(input.Number),
		Body:   input.Body,
		Path:   input.Path,
	})
	if err != nil {
		return nil, err
	}
	return pbPRCommentToModel(resp), nil
}

// UpdatePRComment is the resolver for the updatePRComment field.
func (r *mutationResolver) UpdatePRComment(ctx context.Context, owner string, repo string, commentID string, body string) (*model.PRComment, error) {
	id, err := strconv.ParseUint(commentID, 10, 64)
	if err != nil {
		return nil, err
	}
	resp, err := r.Client.UpdatePRComment(grpcCtx(ctx), &pb.UpdatePRCommentRequest{Owner: owner, Repo: repo, CommentId: id, Body: body})
	if err != nil {
		return nil, err
	}
	return pbPRCommentToModel(resp), nil
}

// DeletePRComment is the resolver for the deletePRComment field.
func (r *mutationResolver) DeletePRComment(ctx context.Context, owner string, repo string, commentID string) (bool, error) {
	id, err := strconv.ParseUint(commentID, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.DeletePRComment(grpcCtx(ctx), &pb.DeletePRCommentRequest{Owner: owner, Repo: repo, CommentId: id})
	return err == nil, err
}

// CreatePRReview is the resolver for the createPRReview field.
func (r *mutationResolver) CreatePRReview(ctx context.Context, input model.CreatePRReviewInput) (*model.PRReview, error) {
	resp, err := r.Client.CreatePRReview(grpcCtx(ctx), &pb.CreatePRReviewRequest{
		Owner:  input.Owner,
		Repo:   input.Repo,
		Number: int32(input.Number),
		State:  input.State,
		Body:   input.Body,
	})
	if err != nil {
		return nil, err
	}
	return pbPRReviewToModel(resp), nil
}

// CreateWebhook is the resolver for the createWebhook field.
func (r *mutationResolver) CreateWebhook(ctx context.Context, input model.CreateWebhookInput) (*model.Webhook, error) {
	resp, err := r.Client.CreateWebhook(grpcCtx(ctx), &pb.CreateWebhookRequest{
		Owner:       input.Owner,
		Repo:        input.Repo,
		Url:         input.URL,
		Events:      input.Events,
		Secret:      input.Secret,
		Active:      input.Active,
		ContentType: input.ContentType,
	})
	if err != nil {
		return nil, err
	}
	return pbWebhookToModel(resp), nil
}

// UpdateWebhook is the resolver for the updateWebhook field.
func (r *mutationResolver) UpdateWebhook(ctx context.Context, input model.UpdateWebhookInput) (*model.Webhook, error) {
	id, err := strconv.ParseUint(input.ID, 10, 64)
	if err != nil {
		return nil, err
	}
	resp, err := r.Client.UpdateWebhook(grpcCtx(ctx), &pb.UpdateWebhookRequest{
		Owner:       input.Owner,
		Repo:        input.Repo,
		Id:          id,
		Url:         input.URL,
		Events:      input.Events,
		Active:      input.Active,
		Secret:      input.Secret,
		ContentType: input.ContentType,
	})
	if err != nil {
		return nil, err
	}
	return pbWebhookToModel(resp), nil
}

// DeleteWebhook is the resolver for the deleteWebhook field.
func (r *mutationResolver) DeleteWebhook(ctx context.Context, owner string, repo *string, id string) (bool, error) {
	wid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.DeleteWebhook(grpcCtx(ctx), &pb.DeleteWebhookRequest{Owner: owner, Repo: repo, Id: wid})
	return err == nil, err
}

// PingWebhook is the resolver for the pingWebhook field.
func (r *mutationResolver) PingWebhook(ctx context.Context, owner string, repo *string, id string) (bool, error) {
	wid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.PingWebhook(grpcCtx(ctx), &pb.PingWebhookRequest{Owner: owner, Repo: repo, Id: wid})
	return err == nil, err
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, username string) (*model.User, error) {
	resp, err := r.Client.GetUser(grpcCtx(ctx), &pb.GetUserRequest{Username: username})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

// GetCurrentUser is the resolver for the getCurrentUser field.
func (r *queryResolver) GetCurrentUser(ctx context.Context) (*model.User, error) {
	resp, err := r.Client.GetCurrentUser(grpcCtx(ctx), &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

// ListUsers is the resolver for the listUsers field.
func (r *queryResolver) ListUsers(ctx context.Context, page *int, perPage *int) (*model.ListUsersResponse, error) {
	resp, err := r.Client.ListUsers(grpcCtx(ctx), &pb.ListUsersRequest{
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListUsersResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, u := range resp.GetUsers() {
		out.Users = append(out.Users, pbUserToModel(u))
	}
	return out, nil
}

// ListSSHKeys is the resolver for the listSSHKeys field.
func (r *queryResolver) ListSSHKeys(ctx context.Context, username string) (*model.ListSSHKeysResponse, error) {
	resp, err := r.Client.ListSSHKeys(grpcCtx(ctx), &pb.ListSSHKeysRequest{Username: username})
	if err != nil {
		return nil, err
	}
	out := &model.ListSSHKeysResponse{}
	for _, k := range resp.GetKeys() {
		out.Keys = append(out.Keys, pbSSHKeyToModel(k))
	}
	return out, nil
}

// GetRepository is the resolver for the getRepository field.
func (r *queryResolver) GetRepository(ctx context.Context, owner string, name string) (*model.Repository, error) {
	resp, err := r.Client.GetRepository(grpcCtx(ctx), &pb.GetRepoRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

// ListRepositories is the resolver for the listRepositories field.
func (r *queryResolver) ListRepositories(ctx context.Context, page *int, perPage *int, includePrivate *bool) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListRepositories(grpcCtx(ctx), &pb.ListReposRequest{
		Page:           int32Ptr(page),
		PerPage:        int32Ptr(perPage),
		IncludePrivate: includePrivate,
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

// ListUserRepositories is the resolver for the listUserRepositories field.
func (r *queryResolver) ListUserRepositories(ctx context.Context, username string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListUserRepositories(grpcCtx(ctx), &pb.ListUserReposRequest{
		Username: username,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

// ListOrgRepositories is the resolver for the listOrgRepositories field.
func (r *queryResolver) ListOrgRepositories(ctx context.Context, orgName string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListOrgRepositories(grpcCtx(ctx), &pb.ListOrgReposRequest{
		OrgName: orgName,
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

// GetRepositoryTree is the resolver for the getRepositoryTree field.
func (r *queryResolver) GetRepositoryTree(ctx context.Context, owner string, name string, ref *string, path *string) (*model.RepoTreeResponse, error) {
	resp, err := r.Client.GetRepositoryTree(grpcCtx(ctx), &pb.GetRepoTreeRequest{
		Owner: owner,
		Name:  name,
		Ref:   ref,
		Path:  path,
	})
	if err != nil {
		return nil, err
	}
	out := &model.RepoTreeResponse{Ref: resp.GetRef()}
	for _, e := range resp.GetEntries() {
		out.Entries = append(out.Entries, pbTreeEntryToModel(e))
	}
	return out, nil
}

// GetFileBlob is the resolver for the getFileBlob field.
func (r *queryResolver) GetFileBlob(ctx context.Context, owner string, name string, path string, ref *string) (*model.FileBlob, error) {
	resp, err := r.Client.GetFileBlob(grpcCtx(ctx), &pb.GetFileBlobRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
	})
	if err != nil {
		return nil, err
	}
	return &model.FileBlob{
		Content:  blobToBase64(resp.GetContent()),
		Size:     int(resp.GetSize()),
		IsBinary: resp.GetIsBinary(),
		Path:     resp.GetPath(),
	}, nil
}

// ListBranches is the resolver for the listBranches field.
func (r *queryResolver) ListBranches(ctx context.Context, owner string, name string) (*model.ListBranchesResponse, error) {
	resp, err := r.Client.ListBranches(grpcCtx(ctx), &pb.ListBranchesRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListBranchesResponse{}
	for _, b := range resp.GetBranches() {
		out.Branches = append(out.Branches, pbBranchToModel(b))
	}
	return out, nil
}

// GetDefaultBranch is the resolver for the getDefaultBranch field.
func (r *queryResolver) GetDefaultBranch(ctx context.Context, owner string, name string) (*model.DefaultBranchResponse, error) {
	resp, err := r.Client.GetDefaultBranch(grpcCtx(ctx), &pb.GetDefaultBranchRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.DefaultBranchResponse{BranchName: resp.GetBranchName()}, nil
}

// ListTags is the resolver for the listTags field.
func (r *queryResolver) ListTags(ctx context.Context, owner string, name string) (*model.ListTagsResponse, error) {
	resp, err := r.Client.ListTags(grpcCtx(ctx), &pb.ListTagsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListTagsResponse{}
	for _, t := range resp.GetTags() {
		out.Tags = append(out.Tags, pbTagToModel(t))
	}
	return out, nil
}

// ListCommits is the resolver for the listCommits field.
func (r *queryResolver) ListCommits(ctx context.Context, owner string, name string, ref *string, limit *int, page *int) (*model.ListCommitsResponse, error) {
	resp, err := r.Client.ListCommits(grpcCtx(ctx), &pb.ListCommitsRequest{
		Owner: owner,
		Name:  name,
		Ref:   ref,
		Limit: int32Ptr(limit),
		Page:  int32Ptr(page),
	})
	if err != nil {
		return nil, err
	}
	return pbListCommitsToModel(resp), nil
}

// GetCommit is the resolver for the getCommit field.
func (r *queryResolver) GetCommit(ctx context.Context, owner string, name string, sha string) (*model.CommitDetail, error) {
	resp, err := r.Client.GetCommit(grpcCtx(ctx), &pb.GetCommitRequest{Owner: owner, Name: name, Sha: sha})
	if err != nil {
		return nil, err
	}
	out := &model.CommitDetail{
		Commit:         pbCommitToModel(resp.GetCommit()),
		TotalAdditions: int(resp.GetTotalAdditions()),
		TotalDeletions: int(resp.GetTotalDeletions()),
		FilesChanged:   int(resp.GetFilesChanged()),
		Patch:          resp.GetPatch(),
	}
	for _, f := range resp.GetFiles() {
		out.Files = append(out.Files, pbFileDiffToModel(f))
	}
	return out, nil
}

// GetRepositoryStats is the resolver for the getRepositoryStats field.
func (r *queryResolver) GetRepositoryStats(ctx context.Context, owner string, name string) (*model.RepoStats, error) {
	resp, err := r.Client.GetRepositoryStats(grpcCtx(ctx), &pb.GetRepoStatsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.RepoStats{
		SizeBytes:        int(resp.GetSizeBytes()),
		CommitCount:      int(resp.GetCommitCount()),
		BranchCount:      int(resp.GetBranchCount()),
		TagCount:         int(resp.GetTagCount()),
		ContributorCount: int(resp.GetContributorCount()),
		LastCommit:       resp.GetLastCommit().AsTime(),
		Stars:            int(resp.GetStars()),
		Forks:            int(resp.GetForks()),
	}, nil
}

// GetCloneURLs is the resolver for the getCloneURLs field.
func (r *queryResolver) GetCloneURLs(ctx context.Context, owner string, name string) (*model.CloneURLs, error) {
	resp, err := r.Client.GetCloneURLs(grpcCtx(ctx), &pb.GetCloneURLsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.CloneURLs{
		SSHURL:  resp.GetSshUrl(),
		HTTPURL: resp.GetHttpUrl(),
		GitURL:  resp.GetGitUrl(),
	}, nil
}

// CompareBranches is the resolver for the compareBranches field.
func (r *queryResolver) CompareBranches(ctx context.Context, owner string, name string, baseBranch string, headBranch string) (*model.CompareResponse, error) {
	resp, err := r.Client.CompareBranches(grpcCtx(ctx), &pb.CompareBranchesRequest{
		Owner:      owner,
		Name:       name,
		BaseBranch: baseBranch,
		HeadBranch: headBranch,
	})
	if err != nil {
		return nil, err
	}
	return pbCompareToModel(resp), nil
}

// CompareCommits is the resolver for the compareCommits field.
func (r *queryResolver) CompareCommits(ctx context.Context, owner string, name string, baseSha string, headSha string) (*model.CompareResponse, error) {
	resp, err := r.Client.CompareCommits(grpcCtx(ctx), &pb.CompareCommitsRequest{
		Owner:   owner,
		Name:    name,
		BaseSha: baseSha,
		HeadSha: headSha,
	})
	if err != nil {
		return nil, err
	}
	return pbCompareToModel(resp), nil
}

// GetFileHistory is the resolver for the getFileHistory field.
func (r *queryResolver) GetFileHistory(ctx context.Context, owner string, name string, path string, ref *string, limit *int) (*model.FileHistoryResponse, error) {
	resp, err := r.Client.GetFileHistory(grpcCtx(ctx), &pb.GetFileHistoryRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
		Limit: int32Ptr(limit),
	})
	if err != nil {
		return nil, err
	}
	out := &model.FileHistoryResponse{}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	return out, nil
}

// SearchCommits is the resolver for the searchCommits field.
func (r *queryResolver) SearchCommits(ctx context.Context, owner string, name string, query string, author *string, ref *string, limit *int) (*model.ListCommitsResponse, error) {
	resp, err := r.Client.SearchCommits(grpcCtx(ctx), &pb.SearchCommitsRequest{
		Owner:  owner,
		Name:   name,
		Query:  query,
		Author: author,
		Ref:    ref,
		Limit:  int32Ptr(limit),
	})
	if err != nil {
		return nil, err
	}
	return pbListCommitsToModel(resp), nil
}

// CheckPath is the resolver for the checkPath field.
func (r *queryResolver) CheckPath(ctx context.Context, owner string, name string, path string, ref *string) (*model.CheckPathResponse, error) {
	resp, err := r.Client.CheckPath(grpcCtx(ctx), &pb.CheckPathRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
	})
	if err != nil {
		return nil, err
	}
	out := &model.CheckPathResponse{
		Exists: resp.GetExists(),
		IsDir:  resp.GetIsDir(),
		IsFile: resp.GetIsFile(),
	}
	if resp.Size != nil {
		s := int(resp.GetSize())
		out.Size = &s
	}
	return out, nil
}

// ListCollaborators is the resolver for the listCollaborators field.
func (r *queryResolver) ListCollaborators(ctx context.Context, owner string, name string) (*model.ListCollaboratorsResponse, error) {
	resp, err := r.Client.ListCollaborators(grpcCtx(ctx), &pb.ListCollaboratorsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListCollaboratorsResponse{}
	for _, c := range resp.GetCollaborators() {
		out.Collaborators = append(out.Collaborators, pbCollaboratorToModel(c))
	}
	return out, nil
}

// GetOrganization is the resolver for the getOrganization field.
func (r *queryResolver) GetOrganization(ctx context.Context, name string) (*model.Organization, error) {
	resp, err := r.Client.GetOrganization(grpcCtx(ctx), &pb.GetOrgRequest{Name: name})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

// ListOrganizations is the resolver for the listOrganizations field.
func (r *queryResolver) ListOrganizations(ctx context.Context, page *int, perPage *int) (*model.ListOrgsResponse, error) {
	resp, err := r.Client.ListOrganizations(grpcCtx(ctx), &pb.ListOrgsRequest{
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgsResponse{Total: int(resp.GetTotal())}
	for _, o := range resp.GetOrganizations() {
		out.Organizations = append(out.Organizations, pbOrgToModel(o))
	}
	return out, nil
}

// ListUserOrganizations is the resolver for the listUserOrganizations field.
func (r *queryResolver) ListUserOrganizations(ctx context.Context, username string) (*model.ListOrgsResponse, error) {
	resp, err := r.Client.ListUserOrganizations(grpcCtx(ctx), &pb.ListUserOrgsRequest{Username: username})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgsResponse{Total: int(resp.GetTotal())}
	for _, o := range resp.GetOrganizations() {
		out.Organizations = append(out.Organizations, pbOrgToModel(o))
	}
	return out, nil
}

// ListOrgMembers is the resolver for the listOrgMembers field.
func (r *queryResolver) ListOrgMembers(ctx context.Context, orgName string) (*model.ListOrgMembersResponse, error) {
	resp, err := r.Client.ListOrgMembers(grpcCtx(ctx), &pb.ListOrgMembersRequest{OrgName: orgName})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgMembersResponse{}
	for _, m := range resp.GetMembers() {
		out.Members = append(out.Members, pbOrgMemberToModel(m))
	}
	return out, nil
}

// GetOrgMembership is the resolver for the getOrgMembership field.
func (r *queryResolver) GetOrgMembership(ctx context.Context, orgName string, username string) (*model.OrgMember, error) {
	resp, err := r.Client.GetOrgMembership(grpcCtx(ctx), &pb.GetOrgMembershipRequest{
		OrgName:  orgName,
		Username: username,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

// CheckStar is the resolver for the checkStar field.
func (r *queryResolver) CheckStar(ctx context.Context, owner string, name string) (*model.CheckStarResponse, error) {
	resp, err := r.Client.CheckStar(grpcCtx(ctx), &pb.CheckStarRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.CheckStarResponse{Starred: resp.GetStarred()}, nil
}

// ListStargazers is the resolver for the listStargazers field.
func (r *queryResolver) ListStargazers(ctx context.Context, owner string, name string, page *int, perPage *int) (*model.ListStargazersResponse, error) {
	resp, err := r.Client.ListStargazers(grpcCtx(ctx), &pb.ListStargazersRequest{
		Owner:   owner,
		Name:    name,
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListStargazersResponse{Total: int(resp.GetTotal())}
	for _, u := range resp.GetUsers() {
		out.Users = append(out.Users, pbUserToModel(u))
	}
	return out, nil
}

// ListStarredRepositories is the resolver for the listStarredRepositories field.
func (r *queryResolver) ListStarredRepositories(ctx context.Context, username string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListStarredRepositories(grpcCtx(ctx), &pb.ListStarredReposRequest{
		Username: username,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

// ListLabels is the resolver for the listLabels field.
func (r *queryResolver) ListLabels(ctx context.Context, owner string, repo string) (*model.ListLabelsResponse, error) {
	resp, err := r.Client.ListLabels(grpcCtx(ctx), &pb.ListLabelsRequest{Owner: owner, Repo: repo})
	if err != nil {
		return nil, err
	}
	out := &model.ListLabelsResponse{}
	for _, l := range resp.GetLabels() {
		out.Labels = append(out.Labels, pbLabelToModel(l))
	}
	return out, nil
}

// GetLabel is the resolver for the getLabel field.
func (r *queryResolver) GetLabel(ctx context.Context, owner string, repo string, name string) (*model.Label, error) {
	resp, err := r.Client.GetLabel(grpcCtx(ctx), &pb.GetLabelRequest{Owner: owner, Repo: repo, Name: name})
	if err != nil {
		return nil, err
	}
	return pbLabelToModel(resp), nil
}

// GetIssue is the resolver for the getIssue field.
func (r *queryResolver) GetIssue(ctx context.Context, owner string, repo string, number int) (*model.Issue, error) {
	resp, err := r.Client.GetIssue(grpcCtx(ctx), &pb.GetIssueRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbIssueToModel(resp), nil
}

// ListIssues is the resolver for the listIssues field.
func (r *queryResolver) ListIssues(ctx context.Context, owner string, repo string, state *string, label *string, assignee *string, author *string, page *int, perPage *int) (*model.ListIssuesResponse, error) {
	resp, err := r.Client.ListIssues(grpcCtx(ctx), &pb.ListIssuesRequest{
		Owner:    owner,
		Repo:     repo,
		State:    state,
		Label:    label,
		Assignee: assignee,
		Author:   author,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListIssuesResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, i := range resp.GetIssues() {
		out.Issues = append(out.Issues, pbIssueToModel(i))
	}
	return out, nil
}

// ListIssueComments is the resolver for the listIssueComments field.
func (r *queryResolver) ListIssueComments(ctx context.Context, owner string, repo string, number int) (*model.ListIssueCommentsResponse, error) {
	resp, err := r.Client.ListIssueComments(grpcCtx(ctx), &pb.ListIssueCommentsRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	out := &model.ListIssueCommentsResponse{}
	for _, c := range resp.GetComments() {
		out.Comments = append(out.Comments, pbIssueCommentToModel(c))
	}
	return out, nil
}

// GetPullRequest is the resolver for the getPullRequest field.
func (r *queryResolver) GetPullRequest(ctx context.Context, owner string, repo string, number int) (*model.PullRequest, error) {
	resp, err := r.Client.GetPullRequest(grpcCtx(ctx), &pb.GetPRRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbPRToModel(resp), nil
}

// ListPullRequests is the resolver for the listPullRequests field.
func (r *queryResolver) ListPullRequests(ctx context.Context, owner string, repo string, state *string, author *string, assignee *string, label *string, base *string, page *int, perPage *int) (*model.ListPRsResponse, error) {
	resp, err := r.Client.ListPullRequests(grpcCtx(ctx), &pb.ListPRsRequest{
		Owner:    owner,
		Repo:     repo,
		State:    state,
		Author:   author,
		Assignee: assignee,
		Label:    label,
		Base:     base,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListPRsResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, pr := range resp.GetPullRequests() {
		out.PullRequests = append(out.PullRequests, pbPRToModel(pr))
	}
	return out, nil
}

// GetPullRequestDiff is the resolver for the getPullRequestDiff field.
func (r *queryResolver) GetPullRequestDiff(ctx context.Context, owner string, repo string, number int) (*model.CompareResponse, error) {
	resp, err := r.Client.GetPullRequestDiff(grpcCtx(ctx), &pb.GetPRDiffRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	return pbCompareToModel(resp), nil
}

// ListPRComments is the resolver for the listPRComments field.
func (r *queryResolver) ListPRComments(ctx context.Context, owner string, repo string, number int) (*model.ListPRCommentsResponse, error) {
	resp, err := r.Client.ListPRComments(grpcCtx(ctx), &pb.ListPRCommentsRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	out := &model.ListPRCommentsResponse{}
	for _, c := range resp.GetComments() {
		out.Comments = append(out.Comments, pbPRCommentToModel(c))
	}
	return out, nil
}

// ListPRReviews is the resolver for the listPRReviews field.
func (r *queryResolver) ListPRReviews(ctx context.Context, owner string, repo string, number int) (*model.ListPRReviewsResponse, error) {
	resp, err := r.Client.ListPRReviews(grpcCtx(ctx), &pb.ListPRReviewsRequest{Owner: owner, Repo: repo, Number: int32(number)})
	if err != nil {
		return nil, err
	}
	out := &model.ListPRReviewsResponse{}
	for _, rv := range resp.GetReviews() {
		out.Reviews = append(out.Reviews, pbPRReviewToModel(rv))
	}
	return out, nil
}

// ListWebhooks is the resolver for the listWebhooks field.
func (r *queryResolver) ListWebhooks(ctx context.Context, owner string, repo *string) (*model.ListWebhooksResponse, error) {
	resp, err := r.Client.ListWebhooks(grpcCtx(ctx), &pb.ListWebhooksRequest{Owner: owner, Repo: repo})
	if err != nil {
		return nil, err
	}
	out := &model.ListWebhooksResponse{}
	for _, w := range resp.GetWebhooks() {
		out.Webhooks = append(out.Webhooks, pbWebhookToModel(w))
	}
	return out, nil
}

// GetWebhook is the resolver for the getWebhook field.
func (r *queryResolver) GetWebhook(ctx context.Context, owner string, repo *string, id string) (*model.Webhook, error) {
	wid, err := strconv.ParseUint(id, 10, 64)
	if err != nil {
		return nil, err
	}
	resp, err := r.Client.GetWebhook(grpcCtx(ctx), &pb.GetWebhookRequest{Owner: owner, Repo: repo, Id: wid})
	if err != nil {
		return nil, err
	}
	return pbWebhookToModel(resp), nil
}

// SearchRepositories is the resolver for the searchRepositories field.
func (r *queryResolver) SearchRepositories(ctx context.Context, query string, language *string, sort *string, order *string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.SearchRepositories(grpcCtx(ctx), &pb.SearchReposRequest{
		Query:    query,
		Language: language,
		Sort:     sort,
		Order:    order,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

// SearchUsers is the resolver for the searchUsers field.
func (r *queryResolver) SearchUsers(ctx context.Context, query string, sort *string, order *string, page *int, perPage *int) (*model.ListUsersResponse, error) {
	resp, err := r.Client.SearchUsers(grpcCtx(ctx), &pb.SearchUsersRequest{
		Query:   query,
		Sort:    sort,
		Order:   order,
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListUsersResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, u := range resp.GetUsers() {
		out.Users = append(out.Users, pbUserToModel(u))
	}
	return out, nil
}

// SearchIssues is the resolver for the searchIssues field.
func (r *queryResolver) SearchIssues(ctx context.Context, query string, state *string, typeArg *string, owner *string, repo *string, author *string, label *string, sort *string, order *string, page *int, perPage *int) (*model.ListIssuesResponse, error) {
	resp, err := r.Client.SearchIssues(grpcCtx(ctx), &pb.SearchIssuesRequest{
		Query:   query,
		State:   state,
		Type:    typeArg,
		Owner:   owner,
		Repo:    repo,
		Author:  author,
		Label:   label,
		Sort:    sort,
		Order:   order,
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListIssuesResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, i := range resp.GetIssues() {
		out.Issues = append(out.Issues, pbIssueToModel(i))
	}
	return out, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func pbListReposToModel(resp *pb.ListReposResponse) *model.ListReposResponse {
	out := &model.ListReposResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, r := range resp.GetRepositories() {
		out.Repositories = append(out.Repositories, pbRepoToModel(r))
	}
	return out
}
func pbListCommitsToModel(resp *pb.ListCommitsResponse) *model.ListCommitsResponse {
	out := &model.ListCommitsResponse{
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
		HasMore: resp.GetHasMore(),
	}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	return out
}
func pbCompareToModel(resp *pb.CompareResponse) *model.CompareResponse {
	out := &model.CompareResponse{
		TotalAdditions: int(resp.GetTotalAdditions()),
		TotalDeletions: int(resp.GetTotalDeletions()),
		FilesChanged:   int(resp.GetFilesChanged()),
		CommitsAhead:   int(resp.GetCommitsAhead()),
	}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	for _, f := range resp.GetFiles() {
		out.Files = append(out.Files, pbFileDiffToModel(f))
	}
	return out
}
*/
