package gql

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"strconv"

	pb "github.com/Gyt-project/backend-api/pkg/grpc"
	"github.com/Gyt-project/backend-api/pkg/gql/model"
	"google.golang.org/protobuf/types/known/emptypb"
)

// ─── Auth ─────────────────────────────────────────────────────────────────────

func (r *mutationResolver) Register(ctx context.Context, input model.RegisterInput) (*model.AuthResponse, error) {
	resp, err := r.Client.Register(grpcCtx(ctx), &pb.RegisterRequest{
		Username:    input.Username,
		Email:       input.Email,
		Password:    input.Password,
		DisplayName: input.DisplayName,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

func (r *mutationResolver) Login(ctx context.Context, input model.LoginInput) (*model.AuthResponse, error) {
	resp, err := r.Client.Login(grpcCtx(ctx), &pb.LoginRequest{
		Login:    input.Login,
		Password: input.Password,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.AuthResponse, error) {
	resp, err := r.Client.RefreshToken(grpcCtx(ctx), &pb.RefreshTokenRequest{
		RefreshToken: refreshToken,
	})
	if err != nil {
		return nil, err
	}
	return pbAuthToModel(resp), nil
}

// ─── Users ────────────────────────────────────────────────────────────────────

func (r *queryResolver) GetUser(ctx context.Context, username string) (*model.User, error) {
	resp, err := r.Client.GetUser(grpcCtx(ctx), &pb.GetUserRequest{Username: username})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

func (r *queryResolver) GetCurrentUser(ctx context.Context) (*model.User, error) {
	resp, err := r.Client.GetCurrentUser(grpcCtx(ctx), &emptypb.Empty{})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

func (r *queryResolver) ListUsers(ctx context.Context, page *int, perPage *int) (*model.ListUsersResponse, error) {
	resp, err := r.Client.ListUsers(grpcCtx(ctx), &pb.ListUsersRequest{
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListUsersResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, u := range resp.GetUsers() {
		out.Users = append(out.Users, pbUserToModel(u))
	}
	return out, nil
}

func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	resp, err := r.Client.UpdateUser(grpcCtx(ctx), &pb.UpdateUserRequest{
		DisplayName: input.DisplayName,
		Bio:         input.Bio,
		AvatarUrl:   input.AvatarURL,
		Email:       input.Email,
		Password:    input.Password,
	})
	if err != nil {
		return nil, err
	}
	return pbUserToModel(resp), nil
}

func (r *mutationResolver) DeleteUser(ctx context.Context, username string) (bool, error) {
	_, err := r.Client.DeleteUser(grpcCtx(ctx), &pb.DeleteUserRequest{Username: username})
	if err != nil {
		return false, err
	}
	return true, nil
}

// ─── SSH Keys ─────────────────────────────────────────────────────────────────

func (r *queryResolver) ListSSHKeys(ctx context.Context, username string) (*model.ListSSHKeysResponse, error) {
	resp, err := r.Client.ListSSHKeys(grpcCtx(ctx), &pb.ListSSHKeysRequest{Username: username})
	if err != nil {
		return nil, err
	}
	out := &model.ListSSHKeysResponse{}
	for _, k := range resp.GetKeys() {
		out.Keys = append(out.Keys, pbSSHKeyToModel(k))
	}
	return out, nil
}

func (r *mutationResolver) AddSSHKey(ctx context.Context, input model.AddSSHKeyInput) (*model.SSHKey, error) {
	resp, err := r.Client.AddSSHKey(grpcCtx(ctx), &pb.AddSSHKeyRequest{
		Name:      input.Name,
		PublicKey: input.PublicKey,
	})
	if err != nil {
		return nil, err
	}
	return pbSSHKeyToModel(resp), nil
}

func (r *mutationResolver) DeleteSSHKey(ctx context.Context, keyID string) (bool, error) {
	id, err := strconv.ParseUint(keyID, 10, 64)
	if err != nil {
		return false, err
	}
	_, err = r.Client.DeleteSSHKey(grpcCtx(ctx), &pb.DeleteSSHKeyRequest{KeyId: id})
	if err != nil {
		return false, err
	}
	return true, nil
}

// ─── Repositories ─────────────────────────────────────────────────────────────

func (r *mutationResolver) CreateRepository(ctx context.Context, input model.CreateRepoInput) (*model.Repository, error) {
	resp, err := r.Client.CreateRepository(grpcCtx(ctx), &pb.CreateRepoRequest{
		Name:        input.Name,
		Description: input.Description,
		IsPrivate:   input.IsPrivate,
		OrgName:     input.OrgName,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

func (r *queryResolver) GetRepository(ctx context.Context, owner string, name string) (*model.Repository, error) {
	resp, err := r.Client.GetRepository(grpcCtx(ctx), &pb.GetRepoRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

func (r *queryResolver) ListRepositories(ctx context.Context, page *int, perPage *int, includePrivate *bool) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListRepositories(grpcCtx(ctx), &pb.ListReposRequest{
		Page:           int32Ptr(page),
		PerPage:        int32Ptr(perPage),
		IncludePrivate: includePrivate,
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

func (r *queryResolver) ListUserRepositories(ctx context.Context, username string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListUserRepositories(grpcCtx(ctx), &pb.ListUserReposRequest{
		Username: username,
		Page:     int32Ptr(page),
		PerPage:  int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

func (r *queryResolver) ListOrgRepositories(ctx context.Context, orgName string, page *int, perPage *int) (*model.ListReposResponse, error) {
	resp, err := r.Client.ListOrgRepositories(grpcCtx(ctx), &pb.ListOrgReposRequest{
		OrgName: orgName,
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	return pbListReposToModel(resp), nil
}

func pbListReposToModel(resp *pb.ListReposResponse) *model.ListReposResponse {
	out := &model.ListReposResponse{
		Total:   int(resp.GetTotal()),
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
	}
	for _, r := range resp.GetRepositories() {
		out.Repositories = append(out.Repositories, pbRepoToModel(r))
	}
	return out
}

func (r *mutationResolver) UpdateRepository(ctx context.Context, input model.UpdateRepoInput) (*model.Repository, error) {
	resp, err := r.Client.UpdateRepository(grpcCtx(ctx), &pb.UpdateRepoRequest{
		Owner:         input.Owner,
		Name:          input.Name,
		Description:   input.Description,
		IsPrivate:     input.IsPrivate,
		DefaultBranch: input.DefaultBranch,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

func (r *mutationResolver) DeleteRepository(ctx context.Context, owner string, name string) (bool, error) {
	_, err := r.Client.DeleteRepository(grpcCtx(ctx), &pb.DeleteRepoRequest{Owner: owner, Name: name})
	if err != nil {
		return false, err
	}
	return true, nil
}

func (r *mutationResolver) RenameRepository(ctx context.Context, input model.RenameRepoInput) (*model.Repository, error) {
	resp, err := r.Client.RenameRepository(grpcCtx(ctx), &pb.RenameRepoRequest{
		Owner:   input.Owner,
		OldName: input.OldName,
		NewName: input.NewName,
	})
	if err != nil {
		return nil, err
	}
	return pbRepoToModel(resp), nil
}

// ─── Repository Content ───────────────────────────────────────────────────────

func (r *queryResolver) GetRepositoryTree(ctx context.Context, owner string, name string, ref *string, path *string) (*model.RepoTreeResponse, error) {
	resp, err := r.Client.GetRepositoryTree(grpcCtx(ctx), &pb.GetRepoTreeRequest{
		Owner: owner,
		Name:  name,
		Ref:   ref,
		Path:  path,
	})
	if err != nil {
		return nil, err
	}
	out := &model.RepoTreeResponse{Ref: resp.GetRef()}
	for _, e := range resp.GetEntries() {
		out.Entries = append(out.Entries, pbTreeEntryToModel(e))
	}
	return out, nil
}

func (r *queryResolver) GetFileBlob(ctx context.Context, owner string, name string, path string, ref *string) (*model.FileBlob, error) {
	resp, err := r.Client.GetFileBlob(grpcCtx(ctx), &pb.GetFileBlobRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
	})
	if err != nil {
		return nil, err
	}
	return &model.FileBlob{
		Content:  blobToBase64(resp.GetContent()),
		Size:     int(resp.GetSize()),
		IsBinary: resp.GetIsBinary(),
		Path:     resp.GetPath(),
	}, nil
}

func (r *queryResolver) ListBranches(ctx context.Context, owner string, name string) (*model.ListBranchesResponse, error) {
	resp, err := r.Client.ListBranches(grpcCtx(ctx), &pb.ListBranchesRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListBranchesResponse{}
	for _, b := range resp.GetBranches() {
		out.Branches = append(out.Branches, pbBranchToModel(b))
	}
	return out, nil
}

func (r *queryResolver) GetDefaultBranch(ctx context.Context, owner string, name string) (*model.DefaultBranchResponse, error) {
	resp, err := r.Client.GetDefaultBranch(grpcCtx(ctx), &pb.GetDefaultBranchRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.DefaultBranchResponse{BranchName: resp.GetBranchName()}, nil
}

func (r *mutationResolver) SetDefaultBranch(ctx context.Context, owner string, name string, branchName string) (*model.DefaultBranchResponse, error) {
	resp, err := r.Client.SetDefaultBranch(grpcCtx(ctx), &pb.SetDefaultBranchRequest{
		Owner:      owner,
		Name:       name,
		BranchName: branchName,
	})
	if err != nil {
		return nil, err
	}
	return &model.DefaultBranchResponse{BranchName: resp.GetBranchName()}, nil
}

func (r *queryResolver) ListTags(ctx context.Context, owner string, name string) (*model.ListTagsResponse, error) {
	resp, err := r.Client.ListTags(grpcCtx(ctx), &pb.ListTagsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListTagsResponse{}
	for _, t := range resp.GetTags() {
		out.Tags = append(out.Tags, pbTagToModel(t))
	}
	return out, nil
}

func (r *mutationResolver) CreateTag(ctx context.Context, input model.CreateTagInput) (*model.TagDetail, error) {
	resp, err := r.Client.CreateTag(grpcCtx(ctx), &pb.CreateTagRequest{
		Owner:   input.Owner,
		Name:    input.Name,
		TagName: input.TagName,
		Target:  input.Target,
		Message: input.Message,
	})
	if err != nil {
		return nil, err
	}
	return &model.TagDetail{
		Tag:    pbTagToModel(resp.GetTag()),
		Commit: pbCommitToModel(resp.GetCommit()),
	}, nil
}

func (r *mutationResolver) DeleteTag(ctx context.Context, owner string, name string, tagName string) (bool, error) {
	_, err := r.Client.DeleteTag(grpcCtx(ctx), &pb.DeleteTagRequest{Owner: owner, Name: name, TagName: tagName})
	if err != nil {
		return false, err
	}
	return true, nil
}

func (r *queryResolver) ListCommits(ctx context.Context, owner string, name string, ref *string, limit *int, page *int) (*model.ListCommitsResponse, error) {
	resp, err := r.Client.ListCommits(grpcCtx(ctx), &pb.ListCommitsRequest{
		Owner: owner,
		Name:  name,
		Ref:   ref,
		Limit: int32Ptr(limit),
		Page:  int32Ptr(page),
	})
	if err != nil {
		return nil, err
	}
	return pbListCommitsToModel(resp), nil
}

func pbListCommitsToModel(resp *pb.ListCommitsResponse) *model.ListCommitsResponse {
	out := &model.ListCommitsResponse{
		Page:    int(resp.GetPage()),
		PerPage: int(resp.GetPerPage()),
		HasMore: resp.GetHasMore(),
	}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	return out
}

func (r *queryResolver) GetCommit(ctx context.Context, owner string, name string, sha string) (*model.CommitDetail, error) {
	resp, err := r.Client.GetCommit(grpcCtx(ctx), &pb.GetCommitRequest{Owner: owner, Name: name, Sha: sha})
	if err != nil {
		return nil, err
	}
	out := &model.CommitDetail{
		Commit:         pbCommitToModel(resp.GetCommit()),
		TotalAdditions: int(resp.GetTotalAdditions()),
		TotalDeletions: int(resp.GetTotalDeletions()),
		FilesChanged:   int(resp.GetFilesChanged()),
		Patch:          resp.GetPatch(),
	}
	for _, f := range resp.GetFiles() {
		out.Files = append(out.Files, pbFileDiffToModel(f))
	}
	return out, nil
}

func (r *queryResolver) GetRepositoryStats(ctx context.Context, owner string, name string) (*model.RepoStats, error) {
	resp, err := r.Client.GetRepositoryStats(grpcCtx(ctx), &pb.GetRepoStatsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.RepoStats{
		SizeBytes:        int(resp.GetSizeBytes()),
		CommitCount:      int(resp.GetCommitCount()),
		BranchCount:      int(resp.GetBranchCount()),
		TagCount:         int(resp.GetTagCount()),
		ContributorCount: int(resp.GetContributorCount()),
		LastCommit:       resp.GetLastCommit().AsTime(),
		Stars:            int(resp.GetStars()),
		Forks:            int(resp.GetForks()),
	}, nil
}

func (r *queryResolver) GetCloneURLs(ctx context.Context, owner string, name string) (*model.CloneURLs, error) {
	resp, err := r.Client.GetCloneURLs(grpcCtx(ctx), &pb.GetCloneURLsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	return &model.CloneURLs{
		SSHURL:  resp.GetSshUrl(),
		HTTPURL: resp.GetHttpUrl(),
		GitURL:  resp.GetGitUrl(),
	}, nil
}

func (r *queryResolver) CompareBranches(ctx context.Context, owner string, name string, baseBranch string, headBranch string) (*model.CompareResponse, error) {
	resp, err := r.Client.CompareBranches(grpcCtx(ctx), &pb.CompareBranchesRequest{
		Owner:      owner,
		Name:       name,
		BaseBranch: baseBranch,
		HeadBranch: headBranch,
	})
	if err != nil {
		return nil, err
	}
	return pbCompareToModel(resp), nil
}

func (r *queryResolver) CompareCommits(ctx context.Context, owner string, name string, baseSha string, headSha string) (*model.CompareResponse, error) {
	resp, err := r.Client.CompareCommits(grpcCtx(ctx), &pb.CompareCommitsRequest{
		Owner:   owner,
		Name:    name,
		BaseSha: baseSha,
		HeadSha: headSha,
	})
	if err != nil {
		return nil, err
	}
	return pbCompareToModel(resp), nil
}

func pbCompareToModel(resp *pb.CompareResponse) *model.CompareResponse {
	out := &model.CompareResponse{
		TotalAdditions: int(resp.GetTotalAdditions()),
		TotalDeletions: int(resp.GetTotalDeletions()),
		FilesChanged:   int(resp.GetFilesChanged()),
		CommitsAhead:   int(resp.GetCommitsAhead()),
	}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	for _, f := range resp.GetFiles() {
		out.Files = append(out.Files, pbFileDiffToModel(f))
	}
	return out
}

func (r *queryResolver) GetFileHistory(ctx context.Context, owner string, name string, path string, ref *string, limit *int) (*model.FileHistoryResponse, error) {
	resp, err := r.Client.GetFileHistory(grpcCtx(ctx), &pb.GetFileHistoryRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
		Limit: int32Ptr(limit),
	})
	if err != nil {
		return nil, err
	}
	out := &model.FileHistoryResponse{}
	for _, c := range resp.GetCommits() {
		out.Commits = append(out.Commits, pbCommitToModel(c))
	}
	return out, nil
}

func (r *queryResolver) SearchCommits(ctx context.Context, owner string, name string, query string, author *string, ref *string, limit *int) (*model.ListCommitsResponse, error) {
	resp, err := r.Client.SearchCommits(grpcCtx(ctx), &pb.SearchCommitsRequest{
		Owner:  owner,
		Name:   name,
		Query:  query,
		Author: author,
		Ref:    ref,
		Limit:  int32Ptr(limit),
	})
	if err != nil {
		return nil, err
	}
	return pbListCommitsToModel(resp), nil
}

func (r *queryResolver) CheckPath(ctx context.Context, owner string, name string, path string, ref *string) (*model.CheckPathResponse, error) {
	resp, err := r.Client.CheckPath(grpcCtx(ctx), &pb.CheckPathRequest{
		Owner: owner,
		Name:  name,
		Path:  path,
		Ref:   ref,
	})
	if err != nil {
		return nil, err
	}
	out := &model.CheckPathResponse{
		Exists: resp.GetExists(),
		IsDir:  resp.GetIsDir(),
		IsFile: resp.GetIsFile(),
	}
	if resp.Size != nil {
		s := int(resp.GetSize())
		out.Size = &s
	}
	return out, nil
}

// ─── Collaborators ─────────────────────────────────────────────────────────────

func (r *queryResolver) ListCollaborators(ctx context.Context, owner string, name string) (*model.ListCollaboratorsResponse, error) {
	resp, err := r.Client.ListCollaborators(grpcCtx(ctx), &pb.ListCollaboratorsRequest{Owner: owner, Name: name})
	if err != nil {
		return nil, err
	}
	out := &model.ListCollaboratorsResponse{}
	for _, c := range resp.GetCollaborators() {
		out.Collaborators = append(out.Collaborators, pbCollaboratorToModel(c))
	}
	return out, nil
}

func (r *mutationResolver) AddCollaborator(ctx context.Context, input model.AddCollaboratorInput) (bool, error) {
	_, err := r.Client.AddCollaborator(grpcCtx(ctx), &pb.AddCollaboratorRequest{
		Owner:       input.Owner,
		Name:        input.Name,
		Username:    input.Username,
		AccessLevel: input.AccessLevel,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

func (r *mutationResolver) RemoveCollaborator(ctx context.Context, owner string, name string, username string) (bool, error) {
	_, err := r.Client.RemoveCollaborator(grpcCtx(ctx), &pb.RemoveCollaboratorRequest{
		Owner:    owner,
		Name:     name,
		Username: username,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

func (r *mutationResolver) UpdateCollaborator(ctx context.Context, input model.UpdateCollaboratorInput) (bool, error) {
	_, err := r.Client.UpdateCollaborator(grpcCtx(ctx), &pb.UpdateCollaboratorRequest{
		Owner:       input.Owner,
		Name:        input.Name,
		Username:    input.Username,
		AccessLevel: input.AccessLevel,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// ─── Organizations ─────────────────────────────────────────────────────────────

func (r *mutationResolver) CreateOrganization(ctx context.Context, input model.CreateOrgInput) (*model.Organization, error) {
	resp, err := r.Client.CreateOrganization(grpcCtx(ctx), &pb.CreateOrgRequest{
		Name:        input.Name,
		DisplayName: input.DisplayName,
		Description: input.Description,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

func (r *queryResolver) GetOrganization(ctx context.Context, name string) (*model.Organization, error) {
	resp, err := r.Client.GetOrganization(grpcCtx(ctx), &pb.GetOrgRequest{Name: name})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

func (r *queryResolver) ListOrganizations(ctx context.Context, page *int, perPage *int) (*model.ListOrgsResponse, error) {
	resp, err := r.Client.ListOrganizations(grpcCtx(ctx), &pb.ListOrgsRequest{
		Page:    int32Ptr(page),
		PerPage: int32Ptr(perPage),
	})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgsResponse{Total: int(resp.GetTotal())}
	for _, o := range resp.GetOrganizations() {
		out.Organizations = append(out.Organizations, pbOrgToModel(o))
	}
	return out, nil
}

func (r *queryResolver) ListUserOrganizations(ctx context.Context, username string) (*model.ListOrgsResponse, error) {
	resp, err := r.Client.ListUserOrganizations(grpcCtx(ctx), &pb.ListUserOrgsRequest{Username: username})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgsResponse{Total: int(resp.GetTotal())}
	for _, o := range resp.GetOrganizations() {
		out.Organizations = append(out.Organizations, pbOrgToModel(o))
	}
	return out, nil
}

func (r *mutationResolver) UpdateOrganization(ctx context.Context, input model.UpdateOrgInput) (*model.Organization, error) {
	resp, err := r.Client.UpdateOrganization(grpcCtx(ctx), &pb.UpdateOrgRequest{
		Name:        input.Name,
		DisplayName: input.DisplayName,
		Description: input.Description,
		AvatarUrl:   input.AvatarURL,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgToModel(resp), nil
}

func (r *mutationResolver) DeleteOrganization(ctx context.Context, name string) (bool, error) {
	_, err := r.Client.DeleteOrganization(grpcCtx(ctx), &pb.DeleteOrgRequest{Name: name})
	if err != nil {
		return false, err
	}
	return true, nil
}

// ─── Org Members ──────────────────────────────────────────────────────────────

func (r *queryResolver) ListOrgMembers(ctx context.Context, orgName string) (*model.ListOrgMembersResponse, error) {
	resp, err := r.Client.ListOrgMembers(grpcCtx(ctx), &pb.ListOrgMembersRequest{OrgName: orgName})
	if err != nil {
		return nil, err
	}
	out := &model.ListOrgMembersResponse{}
	for _, m := range resp.GetMembers() {
		out.Members = append(out.Members, pbOrgMemberToModel(m))
	}
	return out, nil
}

func (r *mutationResolver) AddOrgMember(ctx context.Context, input model.AddOrgMemberInput) (*model.OrgMember, error) {
	resp, err := r.Client.AddOrgMember(grpcCtx(ctx), &pb.AddOrgMemberRequest{
		OrgName:  input.OrgName,
		Username: input.Username,
		Role:     input.Role,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

func (r *mutationResolver) UpdateOrgMember(ctx context.Context, input model.UpdateOrgMemberInput) (*model.OrgMember, error) {
	resp, err := r.Client.UpdateOrgMember(grpcCtx(ctx), &pb.UpdateOrgMemberRequest{
		OrgName:  input.OrgName,
		Username: input.Username,
		Role:     input.Role,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

func (r *mutationResolver) RemoveOrgMember(ctx context.Context, orgName string, username string) (bool, error) {
	_, err := r.Client.RemoveOrgMember(grpcCtx(ctx), &pb.RemoveOrgMemberRequest{
		OrgName:  orgName,
		Username: username,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

func (r *queryResolver) GetOrgMembership(ctx context.Context, orgName string, username string) (*model.OrgMember, error) {
	resp, err := r.Client.GetOrgMembership(grpcCtx(ctx), &pb.GetOrgMembershipRequest{
		OrgName:  orgName,
		Username: username,
	})
	if err != nil {
		return nil, err
	}
	return pbOrgMemberToModel(resp), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
