// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AddCollaboratorInput struct {
	Owner       string `json:"owner"`
	Name        string `json:"name"`
	Username    string `json:"username"`
	AccessLevel string `json:"accessLevel"`
}

type AddOrgMemberInput struct {
	OrgName  string `json:"orgName"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type AddSSHKeyInput struct {
	Name      string `json:"name"`
	PublicKey string `json:"publicKey"`
}

type AuthResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpiresIn    int    `json:"expiresIn"`
	User         *User  `json:"user"`
}

type Author struct {
	Name  string    `json:"name"`
	Email string    `json:"email"`
	When  time.Time `json:"when"`
}

type Branch struct {
	Name      string `json:"name"`
	FullName  string `json:"fullName"`
	CommitSha string `json:"commitSha"`
}

type CheckPathResponse struct {
	Exists bool `json:"exists"`
	IsDir  bool `json:"isDir"`
	IsFile bool `json:"isFile"`
	Size   *int `json:"size,omitempty"`
}

type CloneURLs struct {
	SSHURL  string `json:"sshUrl"`
	HTTPURL string `json:"httpUrl"`
	GitURL  string `json:"gitUrl"`
}

type Collaborator struct {
	Username    string `json:"username"`
	AccessLevel string `json:"accessLevel"`
}

type Commit struct {
	Sha        string   `json:"sha"`
	Author     *Author  `json:"author"`
	Committer  *Author  `json:"committer"`
	Message    string   `json:"message"`
	ParentShas []string `json:"parentShas"`
}

type CommitDetail struct {
	Commit         *Commit     `json:"commit"`
	Files          []*FileDiff `json:"files"`
	TotalAdditions int         `json:"totalAdditions"`
	TotalDeletions int         `json:"totalDeletions"`
	FilesChanged   int         `json:"filesChanged"`
	Patch          string      `json:"patch"`
}

type CompareResponse struct {
	Commits        []*Commit   `json:"commits"`
	Files          []*FileDiff `json:"files"`
	TotalAdditions int         `json:"totalAdditions"`
	TotalDeletions int         `json:"totalDeletions"`
	FilesChanged   int         `json:"filesChanged"`
	CommitsAhead   int         `json:"commitsAhead"`
}

type CreateOrgInput struct {
	Name        string  `json:"name"`
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
}

type CreateRepoInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	IsPrivate   *bool   `json:"isPrivate,omitempty"`
	OrgName     *string `json:"orgName,omitempty"`
}

type CreateTagInput struct {
	Owner   string  `json:"owner"`
	Name    string  `json:"name"`
	TagName string  `json:"tagName"`
	Target  string  `json:"target"`
	Message *string `json:"message,omitempty"`
}

type DefaultBranchResponse struct {
	BranchName string `json:"branchName"`
}

type FileBlob struct {
	Content  string `json:"content"`
	Size     int    `json:"size"`
	IsBinary bool   `json:"isBinary"`
	Path     string `json:"path"`
}

type FileDiff struct {
	Path      string  `json:"path"`
	Additions int     `json:"additions"`
	Deletions int     `json:"deletions"`
	Status    string  `json:"status"`
	OldPath   *string `json:"oldPath,omitempty"`
}

type FileHistoryResponse struct {
	Commits []*Commit `json:"commits"`
}

type ListBranchesResponse struct {
	Branches []*Branch `json:"branches"`
}

type ListCollaboratorsResponse struct {
	Collaborators []*Collaborator `json:"collaborators"`
}

type ListCommitsResponse struct {
	Commits []*Commit `json:"commits"`
	Page    int       `json:"page"`
	PerPage int       `json:"perPage"`
	HasMore bool      `json:"hasMore"`
}

type ListOrgMembersResponse struct {
	Members []*OrgMember `json:"members"`
}

type ListOrgsResponse struct {
	Organizations []*Organization `json:"organizations"`
	Total         int             `json:"total"`
}

type ListReposResponse struct {
	Repositories []*Repository `json:"repositories"`
	Total        int           `json:"total"`
	Page         int           `json:"page"`
	PerPage      int           `json:"perPage"`
}

type ListSSHKeysResponse struct {
	Keys []*SSHKey `json:"keys"`
}

type ListTagsResponse struct {
	Tags []*Tag `json:"tags"`
}

type ListUsersResponse struct {
	Users   []*User `json:"users"`
	Total   int     `json:"total"`
	Page    int     `json:"page"`
	PerPage int     `json:"perPage"`
}

type LoginInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Mutation struct {
}

type OrgMember struct {
	User     *User     `json:"user"`
	Role     string    `json:"role"`
	JoinedAt time.Time `json:"joinedAt"`
}

type Organization struct {
	UUID          string    `json:"uuid"`
	Name          string    `json:"name"`
	DisplayName   string    `json:"displayName"`
	Description   string    `json:"description"`
	AvatarURL     string    `json:"avatarUrl"`
	OwnerUsername string    `json:"ownerUsername"`
	MemberCount   int       `json:"memberCount"`
	RepoCount     int       `json:"repoCount"`
	CreatedAt     time.Time `json:"createdAt"`
}

type Query struct {
}

type RegisterInput struct {
	Username    string  `json:"username"`
	Email       string  `json:"email"`
	Password    string  `json:"password"`
	DisplayName *string `json:"displayName,omitempty"`
}

type RenameRepoInput struct {
	Owner   string `json:"owner"`
	OldName string `json:"oldName"`
	NewName string `json:"newName"`
}

type RepoStats struct {
	SizeBytes        int       `json:"sizeBytes"`
	CommitCount      int       `json:"commitCount"`
	BranchCount      int       `json:"branchCount"`
	TagCount         int       `json:"tagCount"`
	ContributorCount int       `json:"contributorCount"`
	LastCommit       time.Time `json:"lastCommit"`
	Stars            int       `json:"stars"`
	Forks            int       `json:"forks"`
}

type RepoTreeResponse struct {
	Entries []*TreeEntry `json:"entries"`
	Ref     string       `json:"ref"`
}

type Repository struct {
	UUID          string    `json:"uuid"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	DefaultBranch string    `json:"defaultBranch"`
	IsPrivate     bool      `json:"isPrivate"`
	IsFork        bool      `json:"isFork"`
	OwnerType     string    `json:"ownerType"`
	OwnerName     string    `json:"ownerName"`
	Stars         int       `json:"stars"`
	Forks         int       `json:"forks"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

type SSHKey struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	PublicKey string    `json:"publicKey"`
	CreatedAt time.Time `json:"createdAt"`
}

type Tag struct {
	Name      string  `json:"name"`
	FullName  string  `json:"fullName"`
	CommitSha string  `json:"commitSha"`
	Message   *string `json:"message,omitempty"`
}

type TagDetail struct {
	Tag    *Tag    `json:"tag"`
	Commit *Commit `json:"commit"`
}

type TreeEntry struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	Mode        string `json:"mode"`
	Size        int    `json:"size"`
	IsDir       bool   `json:"isDir"`
	IsSubmodule bool   `json:"isSubmodule"`
}

type UpdateCollaboratorInput struct {
	Owner       string `json:"owner"`
	Name        string `json:"name"`
	Username    string `json:"username"`
	AccessLevel string `json:"accessLevel"`
}

type UpdateOrgInput struct {
	Name        string  `json:"name"`
	DisplayName *string `json:"displayName,omitempty"`
	Description *string `json:"description,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
}

type UpdateOrgMemberInput struct {
	OrgName  string `json:"orgName"`
	Username string `json:"username"`
	Role     string `json:"role"`
}

type UpdateRepoInput struct {
	Owner         string  `json:"owner"`
	Name          string  `json:"name"`
	Description   *string `json:"description,omitempty"`
	IsPrivate     *bool   `json:"isPrivate,omitempty"`
	DefaultBranch *string `json:"defaultBranch,omitempty"`
}

type UpdateUserInput struct {
	DisplayName *string `json:"displayName,omitempty"`
	Bio         *string `json:"bio,omitempty"`
	AvatarURL   *string `json:"avatarUrl,omitempty"`
	Email       *string `json:"email,omitempty"`
	Password    *string `json:"password,omitempty"`
}

type User struct {
	UUID        string    `json:"uuid"`
	Username    string    `json:"username"`
	Email       string    `json:"email"`
	DisplayName string    `json:"displayName"`
	Bio         string    `json:"bio"`
	AvatarURL   string    `json:"avatarUrl"`
	IsAdmin     bool      `json:"isAdmin"`
	CreatedAt   time.Time `json:"createdAt"`
}
