// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: pkg/grpc/service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GytService_Register_FullMethodName              = "/gyt.GytService/Register"
	GytService_Login_FullMethodName                 = "/gyt.GytService/Login"
	GytService_RefreshToken_FullMethodName          = "/gyt.GytService/RefreshToken"
	GytService_GetUser_FullMethodName               = "/gyt.GytService/GetUser"
	GytService_GetCurrentUser_FullMethodName        = "/gyt.GytService/GetCurrentUser"
	GytService_UpdateUser_FullMethodName            = "/gyt.GytService/UpdateUser"
	GytService_DeleteUser_FullMethodName            = "/gyt.GytService/DeleteUser"
	GytService_ListUsers_FullMethodName             = "/gyt.GytService/ListUsers"
	GytService_ListSSHKeys_FullMethodName           = "/gyt.GytService/ListSSHKeys"
	GytService_AddSSHKey_FullMethodName             = "/gyt.GytService/AddSSHKey"
	GytService_DeleteSSHKey_FullMethodName          = "/gyt.GytService/DeleteSSHKey"
	GytService_CreateRepository_FullMethodName      = "/gyt.GytService/CreateRepository"
	GytService_GetRepository_FullMethodName         = "/gyt.GytService/GetRepository"
	GytService_ListRepositories_FullMethodName      = "/gyt.GytService/ListRepositories"
	GytService_ListUserRepositories_FullMethodName  = "/gyt.GytService/ListUserRepositories"
	GytService_ListOrgRepositories_FullMethodName   = "/gyt.GytService/ListOrgRepositories"
	GytService_UpdateRepository_FullMethodName      = "/gyt.GytService/UpdateRepository"
	GytService_DeleteRepository_FullMethodName      = "/gyt.GytService/DeleteRepository"
	GytService_RenameRepository_FullMethodName      = "/gyt.GytService/RenameRepository"
	GytService_GetRepositoryTree_FullMethodName     = "/gyt.GytService/GetRepositoryTree"
	GytService_GetFileBlob_FullMethodName           = "/gyt.GytService/GetFileBlob"
	GytService_ListBranches_FullMethodName          = "/gyt.GytService/ListBranches"
	GytService_GetDefaultBranch_FullMethodName      = "/gyt.GytService/GetDefaultBranch"
	GytService_SetDefaultBranch_FullMethodName      = "/gyt.GytService/SetDefaultBranch"
	GytService_ListTags_FullMethodName              = "/gyt.GytService/ListTags"
	GytService_CreateTag_FullMethodName             = "/gyt.GytService/CreateTag"
	GytService_DeleteTag_FullMethodName             = "/gyt.GytService/DeleteTag"
	GytService_ListCommits_FullMethodName           = "/gyt.GytService/ListCommits"
	GytService_GetCommit_FullMethodName             = "/gyt.GytService/GetCommit"
	GytService_GetRepositoryStats_FullMethodName    = "/gyt.GytService/GetRepositoryStats"
	GytService_GetCloneURLs_FullMethodName          = "/gyt.GytService/GetCloneURLs"
	GytService_CompareBranches_FullMethodName       = "/gyt.GytService/CompareBranches"
	GytService_CompareCommits_FullMethodName        = "/gyt.GytService/CompareCommits"
	GytService_GetFileHistory_FullMethodName        = "/gyt.GytService/GetFileHistory"
	GytService_SearchCommits_FullMethodName         = "/gyt.GytService/SearchCommits"
	GytService_CheckPath_FullMethodName             = "/gyt.GytService/CheckPath"
	GytService_ListCollaborators_FullMethodName     = "/gyt.GytService/ListCollaborators"
	GytService_AddCollaborator_FullMethodName       = "/gyt.GytService/AddCollaborator"
	GytService_RemoveCollaborator_FullMethodName    = "/gyt.GytService/RemoveCollaborator"
	GytService_UpdateCollaborator_FullMethodName    = "/gyt.GytService/UpdateCollaborator"
	GytService_CreateOrganization_FullMethodName    = "/gyt.GytService/CreateOrganization"
	GytService_GetOrganization_FullMethodName       = "/gyt.GytService/GetOrganization"
	GytService_ListOrganizations_FullMethodName     = "/gyt.GytService/ListOrganizations"
	GytService_ListUserOrganizations_FullMethodName = "/gyt.GytService/ListUserOrganizations"
	GytService_UpdateOrganization_FullMethodName    = "/gyt.GytService/UpdateOrganization"
	GytService_DeleteOrganization_FullMethodName    = "/gyt.GytService/DeleteOrganization"
	GytService_ListOrgMembers_FullMethodName        = "/gyt.GytService/ListOrgMembers"
	GytService_AddOrgMember_FullMethodName          = "/gyt.GytService/AddOrgMember"
	GytService_UpdateOrgMember_FullMethodName       = "/gyt.GytService/UpdateOrgMember"
	GytService_RemoveOrgMember_FullMethodName       = "/gyt.GytService/RemoveOrgMember"
	GytService_GetOrgMembership_FullMethodName      = "/gyt.GytService/GetOrgMembership"
)

// GytServiceClient is the client API for GytService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GytService is the main backend API consumed by the API gateway.
type GytServiceClient interface {
	// ─── Auth ────────────────────────────────────────────────────────────────
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	// ─── Users ───────────────────────────────────────────────────────────────
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	GetCurrentUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// SSH Keys
	ListSSHKeys(ctx context.Context, in *ListSSHKeysRequest, opts ...grpc.CallOption) (*ListSSHKeysResponse, error)
	AddSSHKey(ctx context.Context, in *AddSSHKeyRequest, opts ...grpc.CallOption) (*SSHKeyResponse, error)
	DeleteSSHKey(ctx context.Context, in *DeleteSSHKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ─── Repositories ────────────────────────────────────────────────────────
	CreateRepository(ctx context.Context, in *CreateRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error)
	GetRepository(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error)
	ListRepositories(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error)
	ListUserRepositories(ctx context.Context, in *ListUserReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error)
	ListOrgRepositories(ctx context.Context, in *ListOrgReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error)
	UpdateRepository(ctx context.Context, in *UpdateRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error)
	DeleteRepository(ctx context.Context, in *DeleteRepoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RenameRepository(ctx context.Context, in *RenameRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error)
	// Repository Content (proxied from git server)
	GetRepositoryTree(ctx context.Context, in *GetRepoTreeRequest, opts ...grpc.CallOption) (*RepoTreeResponse, error)
	GetFileBlob(ctx context.Context, in *GetFileBlobRequest, opts ...grpc.CallOption) (*FileBlobResponse, error)
	ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error)
	GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error)
	SetDefaultBranch(ctx context.Context, in *SetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error)
	ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error)
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetailResponse, error)
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*CommitDetailResponse, error)
	GetRepositoryStats(ctx context.Context, in *GetRepoStatsRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error)
	GetCloneURLs(ctx context.Context, in *GetCloneURLsRequest, opts ...grpc.CallOption) (*CloneURLsResponse, error)
	CompareBranches(ctx context.Context, in *CompareBranchesRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareResponse, error)
	GetFileHistory(ctx context.Context, in *GetFileHistoryRequest, opts ...grpc.CallOption) (*GetFileHistoryResponse, error)
	SearchCommits(ctx context.Context, in *SearchCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error)
	CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error)
	// Collaborators
	ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error)
	AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateCollaborator(ctx context.Context, in *UpdateCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ─── Organizations ───────────────────────────────────────────────────────
	CreateOrganization(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error)
	GetOrganization(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error)
	ListOrganizations(ctx context.Context, in *ListOrgsRequest, opts ...grpc.CallOption) (*ListOrgsResponse, error)
	ListUserOrganizations(ctx context.Context, in *ListUserOrgsRequest, opts ...grpc.CallOption) (*ListOrgsResponse, error)
	UpdateOrganization(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error)
	DeleteOrganization(ctx context.Context, in *DeleteOrgRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Org Members
	ListOrgMembers(ctx context.Context, in *ListOrgMembersRequest, opts ...grpc.CallOption) (*ListOrgMembersResponse, error)
	AddOrgMember(ctx context.Context, in *AddOrgMemberRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error)
	UpdateOrgMember(ctx context.Context, in *UpdateOrgMemberRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error)
	RemoveOrgMember(ctx context.Context, in *RemoveOrgMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetOrgMembership(ctx context.Context, in *GetOrgMembershipRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error)
}

type gytServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGytServiceClient(cc grpc.ClientConnInterface) GytServiceClient {
	return &gytServiceClient{cc}
}

func (c *gytServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, GytService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, GytService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, GytService_RefreshToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, GytService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetCurrentUser(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, GytService_GetCurrentUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, GytService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, GytService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListSSHKeys(ctx context.Context, in *ListSSHKeysRequest, opts ...grpc.CallOption) (*ListSSHKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSSHKeysResponse)
	err := c.cc.Invoke(ctx, GytService_ListSSHKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) AddSSHKey(ctx context.Context, in *AddSSHKeyRequest, opts ...grpc.CallOption) (*SSHKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHKeyResponse)
	err := c.cc.Invoke(ctx, GytService_AddSSHKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) DeleteSSHKey(ctx context.Context, in *DeleteSSHKeyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_DeleteSSHKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CreateRepository(ctx context.Context, in *CreateRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryResponse)
	err := c.cc.Invoke(ctx, GytService_CreateRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetRepository(ctx context.Context, in *GetRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryResponse)
	err := c.cc.Invoke(ctx, GytService_GetRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListRepositories(ctx context.Context, in *ListReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResponse)
	err := c.cc.Invoke(ctx, GytService_ListRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListUserRepositories(ctx context.Context, in *ListUserReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResponse)
	err := c.cc.Invoke(ctx, GytService_ListUserRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListOrgRepositories(ctx context.Context, in *ListOrgReposRequest, opts ...grpc.CallOption) (*ListReposResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReposResponse)
	err := c.cc.Invoke(ctx, GytService_ListOrgRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) UpdateRepository(ctx context.Context, in *UpdateRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryResponse)
	err := c.cc.Invoke(ctx, GytService_UpdateRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) DeleteRepository(ctx context.Context, in *DeleteRepoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_DeleteRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) RenameRepository(ctx context.Context, in *RenameRepoRequest, opts ...grpc.CallOption) (*RepositoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepositoryResponse)
	err := c.cc.Invoke(ctx, GytService_RenameRepository_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetRepositoryTree(ctx context.Context, in *GetRepoTreeRequest, opts ...grpc.CallOption) (*RepoTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoTreeResponse)
	err := c.cc.Invoke(ctx, GytService_GetRepositoryTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetFileBlob(ctx context.Context, in *GetFileBlobRequest, opts ...grpc.CallOption) (*FileBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FileBlobResponse)
	err := c.cc.Invoke(ctx, GytService_GetFileBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListBranches(ctx context.Context, in *ListBranchesRequest, opts ...grpc.CallOption) (*ListBranchesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBranchesResponse)
	err := c.cc.Invoke(ctx, GytService_ListBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetDefaultBranch(ctx context.Context, in *GetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultBranchResponse)
	err := c.cc.Invoke(ctx, GytService_GetDefaultBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) SetDefaultBranch(ctx context.Context, in *SetDefaultBranchRequest, opts ...grpc.CallOption) (*DefaultBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DefaultBranchResponse)
	err := c.cc.Invoke(ctx, GytService_SetDefaultBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListTags(ctx context.Context, in *ListTagsRequest, opts ...grpc.CallOption) (*ListTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTagsResponse)
	err := c.cc.Invoke(ctx, GytService_ListTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*TagDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagDetailResponse)
	err := c.cc.Invoke(ctx, GytService_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListCommits(ctx context.Context, in *ListCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GytService_ListCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*CommitDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitDetailResponse)
	err := c.cc.Invoke(ctx, GytService_GetCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetRepositoryStats(ctx context.Context, in *GetRepoStatsRequest, opts ...grpc.CallOption) (*RepoStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RepoStatsResponse)
	err := c.cc.Invoke(ctx, GytService_GetRepositoryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetCloneURLs(ctx context.Context, in *GetCloneURLsRequest, opts ...grpc.CallOption) (*CloneURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloneURLsResponse)
	err := c.cc.Invoke(ctx, GytService_GetCloneURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CompareBranches(ctx context.Context, in *CompareBranchesRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, GytService_CompareBranches_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CompareCommits(ctx context.Context, in *CompareCommitsRequest, opts ...grpc.CallOption) (*CompareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareResponse)
	err := c.cc.Invoke(ctx, GytService_CompareCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetFileHistory(ctx context.Context, in *GetFileHistoryRequest, opts ...grpc.CallOption) (*GetFileHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFileHistoryResponse)
	err := c.cc.Invoke(ctx, GytService_GetFileHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) SearchCommits(ctx context.Context, in *SearchCommitsRequest, opts ...grpc.CallOption) (*ListCommitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommitsResponse)
	err := c.cc.Invoke(ctx, GytService_SearchCommits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CheckPath(ctx context.Context, in *CheckPathRequest, opts ...grpc.CallOption) (*CheckPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckPathResponse)
	err := c.cc.Invoke(ctx, GytService_CheckPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListCollaborators(ctx context.Context, in *ListCollaboratorsRequest, opts ...grpc.CallOption) (*ListCollaboratorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollaboratorsResponse)
	err := c.cc.Invoke(ctx, GytService_ListCollaborators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) AddCollaborator(ctx context.Context, in *AddCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_AddCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) RemoveCollaborator(ctx context.Context, in *RemoveCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_RemoveCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) UpdateCollaborator(ctx context.Context, in *UpdateCollaboratorRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_UpdateCollaborator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) CreateOrganization(ctx context.Context, in *CreateOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationResponse)
	err := c.cc.Invoke(ctx, GytService_CreateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetOrganization(ctx context.Context, in *GetOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationResponse)
	err := c.cc.Invoke(ctx, GytService_GetOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListOrganizations(ctx context.Context, in *ListOrgsRequest, opts ...grpc.CallOption) (*ListOrgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgsResponse)
	err := c.cc.Invoke(ctx, GytService_ListOrganizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListUserOrganizations(ctx context.Context, in *ListUserOrgsRequest, opts ...grpc.CallOption) (*ListOrgsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgsResponse)
	err := c.cc.Invoke(ctx, GytService_ListUserOrganizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) UpdateOrganization(ctx context.Context, in *UpdateOrgRequest, opts ...grpc.CallOption) (*OrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrganizationResponse)
	err := c.cc.Invoke(ctx, GytService_UpdateOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) DeleteOrganization(ctx context.Context, in *DeleteOrgRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_DeleteOrganization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) ListOrgMembers(ctx context.Context, in *ListOrgMembersRequest, opts ...grpc.CallOption) (*ListOrgMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrgMembersResponse)
	err := c.cc.Invoke(ctx, GytService_ListOrgMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) AddOrgMember(ctx context.Context, in *AddOrgMemberRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgMemberResponse)
	err := c.cc.Invoke(ctx, GytService_AddOrgMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) UpdateOrgMember(ctx context.Context, in *UpdateOrgMemberRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgMemberResponse)
	err := c.cc.Invoke(ctx, GytService_UpdateOrgMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) RemoveOrgMember(ctx context.Context, in *RemoveOrgMemberRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GytService_RemoveOrgMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gytServiceClient) GetOrgMembership(ctx context.Context, in *GetOrgMembershipRequest, opts ...grpc.CallOption) (*OrgMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgMemberResponse)
	err := c.cc.Invoke(ctx, GytService_GetOrgMembership_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GytServiceServer is the server API for GytService service.
// All implementations must embed UnimplementedGytServiceServer
// for forward compatibility.
//
// GytService is the main backend API consumed by the API gateway.
type GytServiceServer interface {
	// ─── Auth ────────────────────────────────────────────────────────────────
	Register(context.Context, *RegisterRequest) (*AuthResponse, error)
	Login(context.Context, *LoginRequest) (*AuthResponse, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*AuthResponse, error)
	// ─── Users ───────────────────────────────────────────────────────────────
	GetUser(context.Context, *GetUserRequest) (*UserResponse, error)
	GetCurrentUser(context.Context, *emptypb.Empty) (*UserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// SSH Keys
	ListSSHKeys(context.Context, *ListSSHKeysRequest) (*ListSSHKeysResponse, error)
	AddSSHKey(context.Context, *AddSSHKeyRequest) (*SSHKeyResponse, error)
	DeleteSSHKey(context.Context, *DeleteSSHKeyRequest) (*emptypb.Empty, error)
	// ─── Repositories ────────────────────────────────────────────────────────
	CreateRepository(context.Context, *CreateRepoRequest) (*RepositoryResponse, error)
	GetRepository(context.Context, *GetRepoRequest) (*RepositoryResponse, error)
	ListRepositories(context.Context, *ListReposRequest) (*ListReposResponse, error)
	ListUserRepositories(context.Context, *ListUserReposRequest) (*ListReposResponse, error)
	ListOrgRepositories(context.Context, *ListOrgReposRequest) (*ListReposResponse, error)
	UpdateRepository(context.Context, *UpdateRepoRequest) (*RepositoryResponse, error)
	DeleteRepository(context.Context, *DeleteRepoRequest) (*emptypb.Empty, error)
	RenameRepository(context.Context, *RenameRepoRequest) (*RepositoryResponse, error)
	// Repository Content (proxied from git server)
	GetRepositoryTree(context.Context, *GetRepoTreeRequest) (*RepoTreeResponse, error)
	GetFileBlob(context.Context, *GetFileBlobRequest) (*FileBlobResponse, error)
	ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error)
	GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*DefaultBranchResponse, error)
	SetDefaultBranch(context.Context, *SetDefaultBranchRequest) (*DefaultBranchResponse, error)
	ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error)
	CreateTag(context.Context, *CreateTagRequest) (*TagDetailResponse, error)
	DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error)
	ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error)
	GetCommit(context.Context, *GetCommitRequest) (*CommitDetailResponse, error)
	GetRepositoryStats(context.Context, *GetRepoStatsRequest) (*RepoStatsResponse, error)
	GetCloneURLs(context.Context, *GetCloneURLsRequest) (*CloneURLsResponse, error)
	CompareBranches(context.Context, *CompareBranchesRequest) (*CompareResponse, error)
	CompareCommits(context.Context, *CompareCommitsRequest) (*CompareResponse, error)
	GetFileHistory(context.Context, *GetFileHistoryRequest) (*GetFileHistoryResponse, error)
	SearchCommits(context.Context, *SearchCommitsRequest) (*ListCommitsResponse, error)
	CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error)
	// Collaborators
	ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error)
	AddCollaborator(context.Context, *AddCollaboratorRequest) (*emptypb.Empty, error)
	RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error)
	UpdateCollaborator(context.Context, *UpdateCollaboratorRequest) (*emptypb.Empty, error)
	// ─── Organizations ───────────────────────────────────────────────────────
	CreateOrganization(context.Context, *CreateOrgRequest) (*OrganizationResponse, error)
	GetOrganization(context.Context, *GetOrgRequest) (*OrganizationResponse, error)
	ListOrganizations(context.Context, *ListOrgsRequest) (*ListOrgsResponse, error)
	ListUserOrganizations(context.Context, *ListUserOrgsRequest) (*ListOrgsResponse, error)
	UpdateOrganization(context.Context, *UpdateOrgRequest) (*OrganizationResponse, error)
	DeleteOrganization(context.Context, *DeleteOrgRequest) (*emptypb.Empty, error)
	// Org Members
	ListOrgMembers(context.Context, *ListOrgMembersRequest) (*ListOrgMembersResponse, error)
	AddOrgMember(context.Context, *AddOrgMemberRequest) (*OrgMemberResponse, error)
	UpdateOrgMember(context.Context, *UpdateOrgMemberRequest) (*OrgMemberResponse, error)
	RemoveOrgMember(context.Context, *RemoveOrgMemberRequest) (*emptypb.Empty, error)
	GetOrgMembership(context.Context, *GetOrgMembershipRequest) (*OrgMemberResponse, error)
	mustEmbedUnimplementedGytServiceServer()
}

// UnimplementedGytServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGytServiceServer struct{}

func (UnimplementedGytServiceServer) Register(context.Context, *RegisterRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedGytServiceServer) Login(context.Context, *LoginRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedGytServiceServer) RefreshToken(context.Context, *RefreshTokenRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedGytServiceServer) GetUser(context.Context, *GetUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedGytServiceServer) GetCurrentUser(context.Context, *emptypb.Empty) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentUser not implemented")
}
func (UnimplementedGytServiceServer) UpdateUser(context.Context, *UpdateUserRequest) (*UserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedGytServiceServer) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGytServiceServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedGytServiceServer) ListSSHKeys(context.Context, *ListSSHKeysRequest) (*ListSSHKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSSHKeys not implemented")
}
func (UnimplementedGytServiceServer) AddSSHKey(context.Context, *AddSSHKeyRequest) (*SSHKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSSHKey not implemented")
}
func (UnimplementedGytServiceServer) DeleteSSHKey(context.Context, *DeleteSSHKeyRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSSHKey not implemented")
}
func (UnimplementedGytServiceServer) CreateRepository(context.Context, *CreateRepoRequest) (*RepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRepository not implemented")
}
func (UnimplementedGytServiceServer) GetRepository(context.Context, *GetRepoRequest) (*RepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepository not implemented")
}
func (UnimplementedGytServiceServer) ListRepositories(context.Context, *ListReposRequest) (*ListReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRepositories not implemented")
}
func (UnimplementedGytServiceServer) ListUserRepositories(context.Context, *ListUserReposRequest) (*ListReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserRepositories not implemented")
}
func (UnimplementedGytServiceServer) ListOrgRepositories(context.Context, *ListOrgReposRequest) (*ListReposResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrgRepositories not implemented")
}
func (UnimplementedGytServiceServer) UpdateRepository(context.Context, *UpdateRepoRequest) (*RepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRepository not implemented")
}
func (UnimplementedGytServiceServer) DeleteRepository(context.Context, *DeleteRepoRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRepository not implemented")
}
func (UnimplementedGytServiceServer) RenameRepository(context.Context, *RenameRepoRequest) (*RepositoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenameRepository not implemented")
}
func (UnimplementedGytServiceServer) GetRepositoryTree(context.Context, *GetRepoTreeRequest) (*RepoTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryTree not implemented")
}
func (UnimplementedGytServiceServer) GetFileBlob(context.Context, *GetFileBlobRequest) (*FileBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileBlob not implemented")
}
func (UnimplementedGytServiceServer) ListBranches(context.Context, *ListBranchesRequest) (*ListBranchesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBranches not implemented")
}
func (UnimplementedGytServiceServer) GetDefaultBranch(context.Context, *GetDefaultBranchRequest) (*DefaultBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDefaultBranch not implemented")
}
func (UnimplementedGytServiceServer) SetDefaultBranch(context.Context, *SetDefaultBranchRequest) (*DefaultBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultBranch not implemented")
}
func (UnimplementedGytServiceServer) ListTags(context.Context, *ListTagsRequest) (*ListTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTags not implemented")
}
func (UnimplementedGytServiceServer) CreateTag(context.Context, *CreateTagRequest) (*TagDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedGytServiceServer) DeleteTag(context.Context, *DeleteTagRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedGytServiceServer) ListCommits(context.Context, *ListCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommits not implemented")
}
func (UnimplementedGytServiceServer) GetCommit(context.Context, *GetCommitRequest) (*CommitDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedGytServiceServer) GetRepositoryStats(context.Context, *GetRepoStatsRequest) (*RepoStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRepositoryStats not implemented")
}
func (UnimplementedGytServiceServer) GetCloneURLs(context.Context, *GetCloneURLsRequest) (*CloneURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCloneURLs not implemented")
}
func (UnimplementedGytServiceServer) CompareBranches(context.Context, *CompareBranchesRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareBranches not implemented")
}
func (UnimplementedGytServiceServer) CompareCommits(context.Context, *CompareCommitsRequest) (*CompareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareCommits not implemented")
}
func (UnimplementedGytServiceServer) GetFileHistory(context.Context, *GetFileHistoryRequest) (*GetFileHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFileHistory not implemented")
}
func (UnimplementedGytServiceServer) SearchCommits(context.Context, *SearchCommitsRequest) (*ListCommitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchCommits not implemented")
}
func (UnimplementedGytServiceServer) CheckPath(context.Context, *CheckPathRequest) (*CheckPathResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckPath not implemented")
}
func (UnimplementedGytServiceServer) ListCollaborators(context.Context, *ListCollaboratorsRequest) (*ListCollaboratorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCollaborators not implemented")
}
func (UnimplementedGytServiceServer) AddCollaborator(context.Context, *AddCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCollaborator not implemented")
}
func (UnimplementedGytServiceServer) RemoveCollaborator(context.Context, *RemoveCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveCollaborator not implemented")
}
func (UnimplementedGytServiceServer) UpdateCollaborator(context.Context, *UpdateCollaboratorRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCollaborator not implemented")
}
func (UnimplementedGytServiceServer) CreateOrganization(context.Context, *CreateOrgRequest) (*OrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrganization not implemented")
}
func (UnimplementedGytServiceServer) GetOrganization(context.Context, *GetOrgRequest) (*OrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrganization not implemented")
}
func (UnimplementedGytServiceServer) ListOrganizations(context.Context, *ListOrgsRequest) (*ListOrgsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrganizations not implemented")
}
func (UnimplementedGytServiceServer) ListUserOrganizations(context.Context, *ListUserOrgsRequest) (*ListOrgsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserOrganizations not implemented")
}
func (UnimplementedGytServiceServer) UpdateOrganization(context.Context, *UpdateOrgRequest) (*OrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrganization not implemented")
}
func (UnimplementedGytServiceServer) DeleteOrganization(context.Context, *DeleteOrgRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteOrganization not implemented")
}
func (UnimplementedGytServiceServer) ListOrgMembers(context.Context, *ListOrgMembersRequest) (*ListOrgMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrgMembers not implemented")
}
func (UnimplementedGytServiceServer) AddOrgMember(context.Context, *AddOrgMemberRequest) (*OrgMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOrgMember not implemented")
}
func (UnimplementedGytServiceServer) UpdateOrgMember(context.Context, *UpdateOrgMemberRequest) (*OrgMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateOrgMember not implemented")
}
func (UnimplementedGytServiceServer) RemoveOrgMember(context.Context, *RemoveOrgMemberRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOrgMember not implemented")
}
func (UnimplementedGytServiceServer) GetOrgMembership(context.Context, *GetOrgMembershipRequest) (*OrgMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrgMembership not implemented")
}
func (UnimplementedGytServiceServer) mustEmbedUnimplementedGytServiceServer() {}
func (UnimplementedGytServiceServer) testEmbeddedByValue()                    {}

// UnsafeGytServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GytServiceServer will
// result in compilation errors.
type UnsafeGytServiceServer interface {
	mustEmbedUnimplementedGytServiceServer()
}

func RegisterGytServiceServer(s grpc.ServiceRegistrar, srv GytServiceServer) {
	// If the following call panics, it indicates UnimplementedGytServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GytService_ServiceDesc, srv)
}

func _GytService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_RefreshToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetCurrentUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetCurrentUser(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListSSHKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSSHKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListSSHKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListSSHKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListSSHKeys(ctx, req.(*ListSSHKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_AddSSHKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSSHKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).AddSSHKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_AddSSHKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).AddSSHKey(ctx, req.(*AddSSHKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_DeleteSSHKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSSHKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).DeleteSSHKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_DeleteSSHKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).DeleteSSHKey(ctx, req.(*DeleteSSHKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CreateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CreateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CreateRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CreateRepository(ctx, req.(*CreateRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetRepository(ctx, req.(*GetRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListRepositories(ctx, req.(*ListReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListUserRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListUserRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListUserRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListUserRepositories(ctx, req.(*ListUserReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListOrgRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgReposRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListOrgRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListOrgRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListOrgRepositories(ctx, req.(*ListOrgReposRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_UpdateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).UpdateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_UpdateRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).UpdateRepository(ctx, req.(*UpdateRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_DeleteRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).DeleteRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_DeleteRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).DeleteRepository(ctx, req.(*DeleteRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_RenameRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).RenameRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_RenameRepository_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).RenameRepository(ctx, req.(*RenameRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetRepositoryTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetRepositoryTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetRepositoryTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetRepositoryTree(ctx, req.(*GetRepoTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetFileBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetFileBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetFileBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetFileBlob(ctx, req.(*GetFileBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListBranches(ctx, req.(*ListBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetDefaultBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDefaultBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetDefaultBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetDefaultBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetDefaultBranch(ctx, req.(*GetDefaultBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_SetDefaultBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).SetDefaultBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_SetDefaultBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).SetDefaultBranch(ctx, req.(*SetDefaultBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListTags(ctx, req.(*ListTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListCommits(ctx, req.(*ListCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetRepositoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepoStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetRepositoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetRepositoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetRepositoryStats(ctx, req.(*GetRepoStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetCloneURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCloneURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetCloneURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetCloneURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetCloneURLs(ctx, req.(*GetCloneURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CompareBranches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareBranchesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CompareBranches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CompareBranches_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CompareBranches(ctx, req.(*CompareBranchesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CompareCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CompareCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CompareCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CompareCommits(ctx, req.(*CompareCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetFileHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFileHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetFileHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetFileHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetFileHistory(ctx, req.(*GetFileHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_SearchCommits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchCommitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).SearchCommits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_SearchCommits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).SearchCommits(ctx, req.(*SearchCommitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CheckPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CheckPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CheckPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CheckPath(ctx, req.(*CheckPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListCollaborators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollaboratorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListCollaborators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListCollaborators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListCollaborators(ctx, req.(*ListCollaboratorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_AddCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).AddCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_AddCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).AddCollaborator(ctx, req.(*AddCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_RemoveCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).RemoveCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_RemoveCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).RemoveCollaborator(ctx, req.(*RemoveCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_UpdateCollaborator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollaboratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).UpdateCollaborator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_UpdateCollaborator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).UpdateCollaborator(ctx, req.(*UpdateCollaboratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_CreateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).CreateOrganization(ctx, req.(*CreateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetOrganization(ctx, req.(*GetOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListOrganizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListOrganizations(ctx, req.(*ListOrgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListUserOrganizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserOrgsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListUserOrganizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListUserOrganizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListUserOrganizations(ctx, req.(*ListUserOrgsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_UpdateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).UpdateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_UpdateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).UpdateOrganization(ctx, req.(*UpdateOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_DeleteOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).DeleteOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_DeleteOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).DeleteOrganization(ctx, req.(*DeleteOrgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_ListOrgMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrgMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).ListOrgMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_ListOrgMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).ListOrgMembers(ctx, req.(*ListOrgMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_AddOrgMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrgMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).AddOrgMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_AddOrgMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).AddOrgMember(ctx, req.(*AddOrgMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_UpdateOrgMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrgMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).UpdateOrgMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_UpdateOrgMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).UpdateOrgMember(ctx, req.(*UpdateOrgMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_RemoveOrgMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrgMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).RemoveOrgMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_RemoveOrgMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).RemoveOrgMember(ctx, req.(*RemoveOrgMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GytService_GetOrgMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrgMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GytServiceServer).GetOrgMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GytService_GetOrgMembership_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GytServiceServer).GetOrgMembership(ctx, req.(*GetOrgMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GytService_ServiceDesc is the grpc.ServiceDesc for GytService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GytService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gyt.GytService",
	HandlerType: (*GytServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _GytService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _GytService_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _GytService_RefreshToken_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _GytService_GetUser_Handler,
		},
		{
			MethodName: "GetCurrentUser",
			Handler:    _GytService_GetCurrentUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _GytService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GytService_DeleteUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _GytService_ListUsers_Handler,
		},
		{
			MethodName: "ListSSHKeys",
			Handler:    _GytService_ListSSHKeys_Handler,
		},
		{
			MethodName: "AddSSHKey",
			Handler:    _GytService_AddSSHKey_Handler,
		},
		{
			MethodName: "DeleteSSHKey",
			Handler:    _GytService_DeleteSSHKey_Handler,
		},
		{
			MethodName: "CreateRepository",
			Handler:    _GytService_CreateRepository_Handler,
		},
		{
			MethodName: "GetRepository",
			Handler:    _GytService_GetRepository_Handler,
		},
		{
			MethodName: "ListRepositories",
			Handler:    _GytService_ListRepositories_Handler,
		},
		{
			MethodName: "ListUserRepositories",
			Handler:    _GytService_ListUserRepositories_Handler,
		},
		{
			MethodName: "ListOrgRepositories",
			Handler:    _GytService_ListOrgRepositories_Handler,
		},
		{
			MethodName: "UpdateRepository",
			Handler:    _GytService_UpdateRepository_Handler,
		},
		{
			MethodName: "DeleteRepository",
			Handler:    _GytService_DeleteRepository_Handler,
		},
		{
			MethodName: "RenameRepository",
			Handler:    _GytService_RenameRepository_Handler,
		},
		{
			MethodName: "GetRepositoryTree",
			Handler:    _GytService_GetRepositoryTree_Handler,
		},
		{
			MethodName: "GetFileBlob",
			Handler:    _GytService_GetFileBlob_Handler,
		},
		{
			MethodName: "ListBranches",
			Handler:    _GytService_ListBranches_Handler,
		},
		{
			MethodName: "GetDefaultBranch",
			Handler:    _GytService_GetDefaultBranch_Handler,
		},
		{
			MethodName: "SetDefaultBranch",
			Handler:    _GytService_SetDefaultBranch_Handler,
		},
		{
			MethodName: "ListTags",
			Handler:    _GytService_ListTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _GytService_CreateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _GytService_DeleteTag_Handler,
		},
		{
			MethodName: "ListCommits",
			Handler:    _GytService_ListCommits_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _GytService_GetCommit_Handler,
		},
		{
			MethodName: "GetRepositoryStats",
			Handler:    _GytService_GetRepositoryStats_Handler,
		},
		{
			MethodName: "GetCloneURLs",
			Handler:    _GytService_GetCloneURLs_Handler,
		},
		{
			MethodName: "CompareBranches",
			Handler:    _GytService_CompareBranches_Handler,
		},
		{
			MethodName: "CompareCommits",
			Handler:    _GytService_CompareCommits_Handler,
		},
		{
			MethodName: "GetFileHistory",
			Handler:    _GytService_GetFileHistory_Handler,
		},
		{
			MethodName: "SearchCommits",
			Handler:    _GytService_SearchCommits_Handler,
		},
		{
			MethodName: "CheckPath",
			Handler:    _GytService_CheckPath_Handler,
		},
		{
			MethodName: "ListCollaborators",
			Handler:    _GytService_ListCollaborators_Handler,
		},
		{
			MethodName: "AddCollaborator",
			Handler:    _GytService_AddCollaborator_Handler,
		},
		{
			MethodName: "RemoveCollaborator",
			Handler:    _GytService_RemoveCollaborator_Handler,
		},
		{
			MethodName: "UpdateCollaborator",
			Handler:    _GytService_UpdateCollaborator_Handler,
		},
		{
			MethodName: "CreateOrganization",
			Handler:    _GytService_CreateOrganization_Handler,
		},
		{
			MethodName: "GetOrganization",
			Handler:    _GytService_GetOrganization_Handler,
		},
		{
			MethodName: "ListOrganizations",
			Handler:    _GytService_ListOrganizations_Handler,
		},
		{
			MethodName: "ListUserOrganizations",
			Handler:    _GytService_ListUserOrganizations_Handler,
		},
		{
			MethodName: "UpdateOrganization",
			Handler:    _GytService_UpdateOrganization_Handler,
		},
		{
			MethodName: "DeleteOrganization",
			Handler:    _GytService_DeleteOrganization_Handler,
		},
		{
			MethodName: "ListOrgMembers",
			Handler:    _GytService_ListOrgMembers_Handler,
		},
		{
			MethodName: "AddOrgMember",
			Handler:    _GytService_AddOrgMember_Handler,
		},
		{
			MethodName: "UpdateOrgMember",
			Handler:    _GytService_UpdateOrgMember_Handler,
		},
		{
			MethodName: "RemoveOrgMember",
			Handler:    _GytService_RemoveOrgMember_Handler,
		},
		{
			MethodName: "GetOrgMembership",
			Handler:    _GytService_GetOrgMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/service.proto",
}
